import type { CanvasObject } from "../hooks/useDesignStore";

export type Template = {
  id: string;
  name: string;
  platform: string;
  width: number;
  height: number;
  objects: Omit<CanvasObject, "id">[];
};

export const TEMPLATES: Template[] = [
  {
    id: "atolye-duyurusu",
    name: "Atölye Duyurusu",
    platform: "instagram-post",
    width: 1080,
    height: 1080,
    objects: [
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#FF6D60",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "shape",
        x: 0,
        y: 540,
        width: 1080,
        height: 540,
        fill: "#e5524a",
        shapeType: "rect",
        opacity: 0.5,
        rotation: 0,
      },
      {
        type: "text",
        x: 100,
        y: 200,
        width: 880,
        text: "YENİ ATÖLYE",
        fontSize: 72,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 100,
        y: 340,
        width: 880,
        text: "Atölye başlığını buraya yazın",
        fontSize: 48,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#ffffff",
        align: "center",
        opacity: 0.9,
        rotation: 0,
      },
      {
        type: "text",
        x: 100,
        y: 800,
        width: 880,
        text: "klemensart.com",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#ffffff",
        align: "center",
        opacity: 0.7,
        rotation: 0,
      },
    ],
  },
  {
    id: "yazi-tanitimi",
    name: "Yazı Tanıtımı",
    platform: "instagram-post",
    width: 1080,
    height: 1080,
    objects: [
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "shape",
        x: 60,
        y: 60,
        width: 960,
        height: 960,
        fill: "#FFFBF7",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 160,
        width: 840,
        text: "YENİ YAZI",
        fontSize: 24,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 240,
        width: 840,
        text: "Yazı başlığını buraya yazın",
        fontSize: 56,
        fontFamily: "Playfair Display",
        fontStyle: "bold",
        fill: "#2D2926",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 880,
        width: 840,
        text: "Klemens Art",
        fontSize: 22,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
    ],
  },
  {
    id: "etkinlik-afisi",
    name: "Etkinlik Afişi",
    platform: "instagram-post",
    width: 1080,
    height: 1080,
    objects: [
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#F5F0EB",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "shape",
        x: 80,
        y: 180,
        width: 4,
        height: 200,
        fill: "#FF6D60",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 180,
        width: 840,
        text: "15 NİSAN 2026",
        fontSize: 32,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 250,
        width: 840,
        text: "Etkinlik Adı",
        fontSize: 64,
        fontFamily: "Playfair Display",
        fontStyle: "bold",
        fill: "#2D2926",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 400,
        width: 840,
        text: "Etkinlik detaylarını buraya yazın. Yer, saat ve diğer bilgileri ekleyin.",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 120,
        y: 920,
        width: 840,
        text: "klemensart.com",
        fontSize: 22,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
    ],
  },
  {
    id: "minimal-alinti",
    name: "Minimal Alıntı",
    platform: "instagram-post",
    width: 1080,
    height: 1080,
    objects: [
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#FFFBF7",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "shape",
        x: 200,
        y: 300,
        width: 680,
        height: 2,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 0.15,
        rotation: 0,
      },
      {
        type: "text",
        x: 140,
        y: 360,
        width: 800,
        text: "\"Buraya güzel bir alıntı yazın.\"",
        fontSize: 44,
        fontFamily: "Playfair Display",
        fontStyle: "italic",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      {
        type: "shape",
        x: 200,
        y: 700,
        width: 680,
        height: 2,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 0.15,
        rotation: 0,
      },
      {
        type: "text",
        x: 140,
        y: 740,
        width: 800,
        text: "— Yazar Adı",
        fontSize: 24,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
    ],
  },
];
