import type { CanvasObject } from "../hooks/useDesignStore";

export type Template = {
  id: string;
  name: string;
  platform: string;
  width: number;
  height: number;
  objects: Omit<CanvasObject, "id">[];
};

export const TEMPLATES: Template[] = [
  // ── Atölye Duyurusu ──────────────────────────────────────
  // Koyu arka plan, üstte görsel alanı, büyük bold başlık,
  // coral bracket etiketler, tarih — "Modern Sanatı Okumak" tarzı
  {
    id: "atolye-duyurusu",
    name: "Atölye Duyurusu",
    platform: "instagram-post",
    width: 1080,
    height: 1440,
    objects: [
      // Koyu arka plan
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1440,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // Görsel alanı placeholder (üst yarı)
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 580,
        fill: "#3d3833",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // "klemens" logo metni sağ üst
      {
        type: "text",
        x: 750,
        y: 40,
        width: 280,
        text: "klemens",
        fontSize: 36,
        fontFamily: "Playfair Display",
        fontStyle: "italic",
        fill: "#ffffff",
        align: "right",
        opacity: 0.9,
        rotation: 0,
      },
      // Küçük giriş metni (italic)
      {
        type: "text",
        x: 80,
        y: 620,
        width: 920,
        text: "\"Bunu ben de çizerdim!\" dediğimiz\neserler aslında bize ne anlatıyor?",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "italic",
        fill: "#b0a99f",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Ana başlık — büyük, bold, uppercase
      {
        type: "text",
        x: 80,
        y: 730,
        width: 920,
        text: "MODERN SANATI\nOKUMAK",
        fontSize: 88,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Açıklama metni
      {
        type: "text",
        x: 80,
        y: 960,
        width: 920,
        text: "Anlamsız görünenin ardındaki felsefeyi\nkeşfedeceğimiz 10 haftalık zihin yolculuğu.",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#b0a99f",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Coral bracket etiketler
      {
        type: "text",
        x: 80,
        y: 1120,
        width: 920,
        text: "[ KLEMENS LOCA ]  •  [ 10 HAFTALIK ATÖLYE ]",
        fontSize: 22,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Tarih
      {
        type: "text",
        x: 80,
        y: 1180,
        width: 920,
        text: "25 Mart'ta Başlıyor",
        fontSize: 32,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
    ],
  },

  // ── Yazı Tanıtımı ────────────────────────────────────────
  // Açık krem arka plan, üstte görsel, coral kategori etiketi,
  // büyük body text, yazar adı — editorial stil
  {
    id: "yazi-tanitimi",
    name: "Yazı Tanıtımı",
    platform: "instagram-post",
    width: 1080,
    height: 1440,
    objects: [
      // Krem arka plan
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1440,
        fill: "#FFFBF7",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // Görsel alanı placeholder
      {
        type: "shape",
        x: 80,
        y: 60,
        width: 920,
        height: 520,
        fill: "#F5F0EB",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // Kategori etiketi — coral, uppercase, letter-spaced
      {
        type: "text",
        x: 80,
        y: 640,
        width: 920,
        text: "K Ü L T Ü R   &   S A N A T",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Yazı gövde metni — büyük, okunabilir
      {
        type: "text",
        x: 80,
        y: 710,
        width: 920,
        text: "Romantiklere göre yalnızlık, ayrıcalıklı bir ötekilik, bir doğayla temas etme alanıydı ve pek çok anlamda anlatının başlayabilmesinin ön koşulu olarak görülürdü.",
        fontSize: 34,
        fontFamily: "Playfair Display",
        fontStyle: "normal",
        fill: "#2D2926",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
      // Yazar adı
      {
        type: "text",
        x: 80,
        y: 1320,
        width: 920,
        text: "— Yazar Adı",
        fontSize: 26,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "left",
        opacity: 1,
        rotation: 0,
      },
    ],
  },

  // ── Seminer Afişi ─────────────────────────────────────────
  // Krem/kağıt arka plan, büyük serif başlık, coral badge'ler,
  // ortalamalı açıklama, tarih/saat, yürütücü — Caravaggio tarzı
  {
    id: "seminer-afisi",
    name: "Seminer Afişi",
    platform: "instagram-post",
    width: 1080,
    height: 1440,
    objects: [
      // Kağıt dokusu arka plan
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1440,
        fill: "#F5F0EB",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // Büyük serif başlık
      {
        type: "text",
        x: 60,
        y: 80,
        width: 960,
        text: "Caravaggio",
        fontSize: 96,
        fontFamily: "Playfair Display",
        fontStyle: "bold",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Alt başlık
      {
        type: "text",
        x: 60,
        y: 200,
        width: 700,
        text: "Sanat Tarihi",
        fontSize: 56,
        fontFamily: "Playfair Display",
        fontStyle: "normal",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // "Seminer" coral badge
      {
        type: "shape",
        x: 600,
        y: 205,
        width: 200,
        height: 52,
        fill: "#FF6D60",
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 610,
        y: 215,
        width: 180,
        text: "Seminer",
        fontSize: 28,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // "ONLINE" badge — coral outlined
      {
        type: "shape",
        x: 280,
        y: 300,
        width: 180,
        height: 44,
        fill: "transparent",
        stroke: "#FF6D60",
        strokeWidth: 2,
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 280,
        y: 308,
        width: 180,
        text: "ONLINE",
        fontSize: 20,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // "TEK OTURUM" badge
      {
        type: "shape",
        x: 490,
        y: 300,
        width: 220,
        height: 44,
        fill: "transparent",
        stroke: "#FF6D60",
        strokeWidth: 2,
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 490,
        y: 308,
        width: 220,
        text: "TEK OTURUM",
        fontSize: 20,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#FF6D60",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Açıklama metni — ortalı
      {
        type: "text",
        x: 100,
        y: 400,
        width: 880,
        text: "Kendi karanlığından kaçarken\nBarok sanatın ışığını yaratan\nCaravaggio'nun yükselişi ve düşüşü.",
        fontSize: 30,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Tarih — coral badge
      {
        type: "shape",
        x: 60,
        y: 580,
        width: 380,
        height: 50,
        fill: "#FF6D60",
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 70,
        y: 590,
        width: 360,
        text: "16 ŞUBAT PAZARTESİ",
        fontSize: 24,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Saat — coral badge
      {
        type: "shape",
        x: 60,
        y: 650,
        width: 260,
        height: 50,
        fill: "#FF6D60",
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 70,
        y: 660,
        width: 240,
        text: "20:30 - 22:30",
        fontSize: 24,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "bold",
        fill: "#ffffff",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Yürütücü — coral outlined
      {
        type: "shape",
        x: 60,
        y: 1300,
        width: 500,
        height: 50,
        fill: "transparent",
        stroke: "#FF6D60",
        strokeWidth: 2,
        shapeType: "rect",
        cornerRadius: 4,
        opacity: 1,
        rotation: 0,
      },
      {
        type: "text",
        x: 70,
        y: 1310,
        width: 480,
        text: "Atölye Yürütücüsü: Kerem Hun",
        fontSize: 22,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
    ],
  },

  // ── Minimal Alıntı ────────────────────────────────────────
  // Krem arka plan, ince çizgiler, ortada italic serif alıntı
  {
    id: "minimal-alinti",
    name: "Minimal Alıntı",
    platform: "instagram-post",
    width: 1080,
    height: 1440,
    objects: [
      // Krem arka plan
      {
        type: "shape",
        x: 0,
        y: 0,
        width: 1080,
        height: 1440,
        fill: "#FFFBF7",
        shapeType: "rect",
        opacity: 1,
        rotation: 0,
      },
      // Üst ince çizgi
      {
        type: "shape",
        x: 200,
        y: 450,
        width: 680,
        height: 2,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 0.12,
        rotation: 0,
      },
      // Alıntı metni
      {
        type: "text",
        x: 120,
        y: 500,
        width: 840,
        text: "\"Sanat, doğanın insana\ntuttuğu aynadır.\"",
        fontSize: 48,
        fontFamily: "Playfair Display",
        fontStyle: "italic",
        fill: "#2D2926",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // Alt ince çizgi
      {
        type: "shape",
        x: 200,
        y: 850,
        width: 680,
        height: 2,
        fill: "#2D2926",
        shapeType: "rect",
        opacity: 0.12,
        rotation: 0,
      },
      // Yazar adı
      {
        type: "text",
        x: 120,
        y: 890,
        width: 840,
        text: "— Yazar Adı",
        fontSize: 24,
        fontFamily: "Plus Jakarta Sans",
        fontStyle: "normal",
        fill: "#8C857E",
        align: "center",
        opacity: 1,
        rotation: 0,
      },
      // "klemens" alt
      {
        type: "text",
        x: 120,
        y: 1340,
        width: 840,
        text: "klemens",
        fontSize: 28,
        fontFamily: "Playfair Display",
        fontStyle: "italic",
        fill: "#b0a99f",
        align: "center",
        opacity: 0.6,
        rotation: 0,
      },
    ],
  },
];
