import type { Artwork, RoomConfig, DoorConnection } from "./types";

// ── Layout constants ──
export const ROOM_SIZE = 10;
export const WALL_HEIGHT = 4.5;
export const DOOR_WIDTH = 2.8;
export const DOOR_HEIGHT = 3.5;

// ── 21 artworks (identical to v1) ──
export const ARTWORKS: Artwork[] = [
  // ── Afrodisias (4) ──
  {
    id: 1,
    title: "Afrodisias'ta Sessizlik",
    location: "Afrodisias, Aydin",
    photographer: "Theo Atay",
    note: "UNESCO Dunya Mirasi'nin mermer sokaklari, binlerce yillik heykeltiraslarin ellerinden cikmis izleri tasiyor. Burada taslar konusuyor, insanlar susuyor.",
    info: "Afrodisias, antik donemin en unlu heykeltraslik okuluna ev sahipligi yapmis bir kenttir. 2017'de UNESCO Dunya Mirasi listesine alinmistir.",
    color: "#5B3A6B",
    accent: "#9B6BB0",
    image: "/sergi/en-sessiz-zaman-v2/afrodisias-1.webp",
  },
  {
    id: 2,
    title: "Mermer Avlu",
    location: "Afrodisias, Aydin",
    photographer: "Theo Atay",
    note: "Tetrapylon'un dort sutunu arasinda ruzgar bile yavasliyor. Ask tanricasinin kentinde, yalnizlik bile zarif.",
    info: "Afrodisias Tetrapylon'u, kentin anitsal giris kapisidir. Dort sutun grubundan olusan bu yapi, MS 2. yuzyilda insa edilmistir.",
    color: "#6B5B3A",
    accent: "#B09B6B",
    image: "/sergi/en-sessiz-zaman-v2/afrodisias-2.webp",
  },
  {
    id: 3,
    title: "Stadyumda Yanki",
    location: "Afrodisias, Aydin",
    photographer: "Theo Atay",
    note: "Otuz bin kisilik stadyumda tek bir ses: ruzgar. Tribunler bombos, ama taslar hala tezahurat bekliyor.",
    info: "Afrodisias Stadyumu, 262 metre uzunlugu ve 59 metre genisligiyle Roma doneminin en buyuk stadyumlarindan biridir.",
    color: "#3A5B6B",
    accent: "#6B9BB0",
    image: "/sergi/en-sessiz-zaman-v2/afrodisias-3.webp",
  },
  {
    id: 4,
    title: "Heykeltirasin Mirasi",
    location: "Afrodisias, Aydin",
    photographer: "Theo Atay",
    note: "Mermer bloklardan yuzler, bedenler dogmus bir zamanlar. Simdi yarim kalmis heykeller, tamamlanmayi bekleyen hikayeler gibi duruyor.",
    info: "Afrodisias heykeltraslik okulu, Roma Imparatorlugu'nun en onemli mermer isleme merkeziydi.",
    color: "#6B3A5B",
    accent: "#B06B9B",
    image: "/sergi/en-sessiz-zaman-v2/afrodisias-4.webp",
  },
  // ── Aizanoi (3) ──
  {
    id: 5,
    title: "Zeus'un Evi",
    location: "Aizanoi, Kutahya",
    photographer: "Theo Atay",
    note: "Anadolu'nun en iyi korunmus Zeus Tapinagi, iki bin yildir gokyuzune bakiyor. Tanrilar gitti, tapinak kaldi.",
    info: "Aizanoi Zeus Tapinagi, Anadolu'daki en iyi korunmus Roma tapinagidir. Alt katinda Kybele'ye adanmis bir magara tapinagi barindirir.",
    color: "#8B6914",
    accent: "#D4A843",
    image: "/sergi/en-sessiz-zaman-v2/aizanoi-1.webp",
  },
  {
    id: 6,
    title: "Stadyum ve Tiyatro",
    location: "Aizanoi, Kutahya",
    photographer: "Theo Atay",
    note: "Dunyanin bilinen tek stadyum-tiyatro kompleksi. Iki amaci tek yapida birlestiren muhendislik harikasi, simdi sessizlige teslim.",
    info: "Aizanoi, dunyada stadyum ve tiyatronun ic ice gectigi tek antik kenttir.",
    color: "#4A6741",
    accent: "#7BA370",
    image: "/sergi/en-sessiz-zaman-v2/aizanoi-2.webp",
  },
  {
    id: 7,
    title: "Penkalas Kiyisinda",
    location: "Aizanoi, Kutahya",
    photographer: "Theo Atay",
    note: "Antik koprunun altindan akan Penkalas Cayi, iki bin yildir ayni sarkiyi soyluyor. Degisen yalnizca dinleyenler.",
    info: "Aizanoi'nin antik kopruleri, kenti ikiye bolen Penkalas Cayi uzerinde insa edilmistir.",
    color: "#5B6B3A",
    accent: "#9BB06B",
    image: "/sergi/en-sessiz-zaman-v2/aizanoi-3.webp",
  },
  // ── Asklepion (1) ──
  {
    id: 8,
    title: "Sifanin Sessizligi",
    location: "Asklepion, Bergama",
    photographer: "Theo Atay",
    note: "Antik dunyanin en unlu sifa merkezi. Hastalar burada ruyalariyla iyilesirdi. Simdi ruya goren yalnizca ruzgar.",
    info: "Bergama Asklepion'u, antik cagin en onemli saglik merkezlerinden biriydi. Modern psikoterapinin oncusu sayilir.",
    color: "#3A6B5B",
    accent: "#6BB09B",
    image: "/sergi/en-sessiz-zaman-v2/asklepion-1.webp",
  },
  // ── Assos (1) ──
  {
    id: 9,
    title: "Athena'nin Bakisi",
    location: "Assos, Canakkale",
    photographer: "Theo Atay",
    note: "Ege'nin uzerinde yukselen Athena Tapinagi'ndan Midilli Adasi'na bakis. Aristoteles burada bir okul kurmustu.",
    info: "Assos Athena Tapinagi, Arkaik donemde insa edilen tek Dor tapinagidir. Aristoteles MO 347-345 yillarinda burada bir felsefe okulu kurmustur.",
    color: "#14698B",
    accent: "#43A8D4",
    image: "/sergi/en-sessiz-zaman-v2/assos-1.webp",
  },
  // ── Blaundus (1) ──
  {
    id: 10,
    title: "Kanyonun Kiyisinda",
    location: "Blaundus, Usak",
    photographer: "Theo Atay",
    note: "Ulubey Kanyonu'nun kenarinda, ucurumla yarisan sutunlar. Dunyanin unuttugu bir kent, kendini ucurumda hatirlıyor.",
    info: "Blaundus, Usak'in Ulubey ilcesinde, kanyonun kenarinda kurulmus antik bir kenttir.",
    color: "#8B4513",
    accent: "#CD853F",
    image: "/sergi/en-sessiz-zaman-v2/blaundus-1.webp",
  },
  // ── Catalhoyuk (2) ──
  {
    id: 11,
    title: "Ilk Ev",
    location: "Catalhoyuk, Konya",
    photographer: "Theo Atay",
    note: "Dunyanin en eski yerlesimlerinden biri. Kapisi olmayan evler, damdan girilen odalar. Insanligin ilk 'mahalle'si.",
    info: "Catalhoyuk, MO 7500-5700 yillarina tarihlenen, dunyanin en eski ve en buyuk Neolitik yerlesimlerinden biridir.",
    color: "#6B5B4A",
    accent: "#B09B8A",
    image: "/sergi/en-sessiz-zaman-v2/catalhoyuk-1.webp",
  },
  {
    id: 12,
    title: "Neolitik Katmanlar",
    location: "Catalhoyuk, Konya",
    photographer: "Theo Atay",
    note: "Her katman bir nesil, her duvar bir hikaye. Binlerce yil ust uste yasamis insanlarin izleri, topragin altinda sakli.",
    info: "Catalhoyuk'te 18 yerlesim katmani tespit edilmistir. En kalabalik doneminde 8.000'e kadar insanin yasadigi tahmin edilmektedir.",
    color: "#5B4A3A",
    accent: "#9B8A6B",
    image: "/sergi/en-sessiz-zaman-v2/catalhoyuk-2.webp",
  },
  // ── Kibyra (2) ──
  {
    id: 13,
    title: "Gladyatorun Arenasi",
    location: "Kibyra, Burdur",
    photographer: "Theo Atay",
    note: "Gladyatorlerin kaniyla sulanan arena, simdi kirlangıclara ev sahipligi yapiyor.",
    info: "Kibyra, Burdur'un Golhisar ilcesinde yer alan antik kenttir. 2015 yilinda kesfedilen gladyator mozaikleriyle dunya gundemine oturmustur.",
    color: "#6B3A3A",
    accent: "#B06B6B",
    image: "/sergi/en-sessiz-zaman-v2/kibyra-1.webp",
  },
  {
    id: 14,
    title: "Medusa'nin Gozleri",
    location: "Kibyra, Burdur",
    photographer: "Theo Atay",
    note: "Tasa donmus yuzler, zamana meydan okuyor. Medusa'nin bakisi bile buranin yalnizligini kiramadi.",
    info: "Kibyra'nin Medusa kabartmalari, Roma doneminin en etkileyici tas isçiligi ornekleri arasindadir.",
    color: "#4A3A6B",
    accent: "#8A6BB0",
    image: "/sergi/en-sessiz-zaman-v2/kibyra-2.webp",
  },
  // ── Laodikeia (4) ──
  {
    id: 15,
    title: "Yedi Kiliseden Biri",
    location: "Laodikeia, Denizli",
    photographer: "Theo Atay",
    note: "Kutsal Kitab'in yedi kilisesinden biri buradaydi. Simdi ruzgara vaaz veriyor.",
    info: "Laodikeia, Vahiy Kitabi'nda adi gecen yedi kiliseden biridir. Tekstil, tip ve bankacilikla zenginlesmis onemli bir Roma sehriydi.",
    color: "#3A4A6B",
    accent: "#6B8AB0",
    image: "/sergi/en-sessiz-zaman-v2/laodikeia-1.webp",
  },
  {
    id: 16,
    title: "Antik Cadde",
    location: "Laodikeia, Denizli",
    photographer: "Theo Atay",
    note: "Sutunlu caddenin sonunda ne var? Iki bin yil once bir pazar, bir hamam, bir yasam. Simdi yalnizca ufuk cizgisi.",
    info: "Laodikeia'nin sutunlu caddesi, kentin ana arteriydi. Roma kentsel planlamasinin guzel bir ornegidir.",
    color: "#6B4A3A",
    accent: "#B08A6B",
    image: "/sergi/en-sessiz-zaman-v2/laodikeia-2.webp",
  },
  {
    id: 17,
    title: "Stadyumda Golgeler",
    location: "Laodikeia, Denizli",
    photographer: "Theo Atay",
    note: "Gunes alcaldikca stadyumun golgeleri uzuyor. Seyirciler coktan gitti, ama golgeler hala tribunlerde oturuyor.",
    info: "Laodikeia Stadyumu, 250 metre uzunluguyla antik dunyanin buyuk stadyumlarindan biriydi.",
    color: "#4A6B3A",
    accent: "#8AB06B",
    image: "/sergi/en-sessiz-zaman-v2/laodikeia-3.webp",
  },
  {
    id: 18,
    title: "Nymphaeum Sulari",
    location: "Laodikeia, Denizli",
    photographer: "Theo Atay",
    note: "Cesmenin suyu coktan kurudu, ama havuzun mermer kenarlari hala piril piril. Su gitmis, guzellik kalmis.",
    info: "Laodikeia'daki anitsal cesmeler, kentin su sisteminin gorkemini yansitir.",
    color: "#3A6B4A",
    accent: "#6BB08A",
    image: "/sergi/en-sessiz-zaman-v2/laodikeia-4.webp",
  },
  // ── Sagalassos (3) ──
  {
    id: 19,
    title: "Dagin Zirvesinde Roma",
    location: "Sagalassos, Burdur",
    photographer: "Theo Atay",
    note: "1.500 metre yukseklikte, bulutlarin arasinda bir Roma kenti. Burada yalnizlik bir tercih degil, cografyanin dayattigi bir kader.",
    info: "Sagalassos, Burdur'un Aglasun ilcesinde, Toros Daglari'nin eteklerinde kurulmus antik bir kenttir. 'Daglarin Roma'si' olarak anilir.",
    color: "#3A5B6B",
    accent: "#6B9BB0",
    image: "/sergi/en-sessiz-zaman-v2/sagalassos-1.webp",
  },
  {
    id: 20,
    title: "Antoninler Cesmesi",
    location: "Sagalassos, Burdur",
    photographer: "Theo Atay",
    note: "Iki bin yil sonra yeniden akan su. Arkeologlar cesmeyi restore etti ve su, sanki hic duramamis gibi akmaya basladi.",
    info: "Antoninler Cesmesi, MS 2. yuzyilda Imparator Marcus Aurelius doneminde insa edilmistir. 2010'da restore edilerek yeniden suyla bulusmustur.",
    color: "#5B3A4A",
    accent: "#9B6B8A",
    image: "/sergi/en-sessiz-zaman-v2/sagalassos-2.webp",
  },
  {
    id: 21,
    title: "Bulutlarin Altinda",
    location: "Sagalassos, Burdur",
    photographer: "Theo Atay",
    note: "Sagalassos'un tiyatrosu bulutlara o kadar yakin ki, sahneye cikan aktorler gokyuzune dokunabilirmis gibi.",
    info: "Sagalassos Tiyatrosu, 9.000 kisi kapasitesiyle dag yamacina oyulmustur.",
    color: "#4A5B3A",
    accent: "#8A9B6B",
    image: "/sergi/en-sessiz-zaman-v2/sagalassos-3.webp",
  },
];

// ── 6 Room configurations ──
// Grid: 2 columns x 3 rows
// Room centers: col*ROOM_SIZE, 0, -row*ROOM_SIZE
export const ROOMS: RoomConfig[] = [
  {
    id: 0,
    name: "Afrodisias",
    subtitle: "4 eser",
    artworkIds: [1, 2, 3, 4],
    gridCol: 0,
    gridRow: 0,
    slots: [
      { wallSide: "north", offset: -0.45, height: 1.8 },
      { wallSide: "north", offset: 0.45, height: 1.8 },
      { wallSide: "west", offset: -0.45, height: 1.8 },
      { wallSide: "west", offset: 0.45, height: 1.8 },
    ],
  },
  {
    id: 1,
    name: "Aizanoi",
    subtitle: "3 eser",
    artworkIds: [5, 6, 7],
    gridCol: 1,
    gridRow: 0,
    slots: [
      { wallSide: "north", offset: -0.45, height: 1.8 },
      { wallSide: "north", offset: 0.45, height: 1.8 },
      { wallSide: "east", offset: 0, height: 1.8 },
    ],
  },
  {
    id: 2,
    name: "Asklepion / Assos / Blaundus",
    subtitle: "3 eser",
    artworkIds: [8, 9, 10],
    gridCol: 0,
    gridRow: 1,
    slots: [
      { wallSide: "west", offset: -0.45, height: 1.8 },
      { wallSide: "west", offset: 0.45, height: 1.8 },
      { wallSide: "south", offset: -0.7, height: 1.8 },
    ],
  },
  {
    id: 3,
    name: "Catalhoyuk / Kibyra",
    subtitle: "4 eser",
    artworkIds: [11, 12, 13, 14],
    gridCol: 1,
    gridRow: 1,
    slots: [
      { wallSide: "east", offset: -0.45, height: 1.8 },
      { wallSide: "east", offset: 0.45, height: 1.8 },
      { wallSide: "south", offset: 0.7, height: 1.8 },
      { wallSide: "north", offset: 0.7, height: 1.8 },
    ],
  },
  {
    id: 4,
    name: "Laodikeia",
    subtitle: "4 eser",
    artworkIds: [15, 16, 17, 18],
    gridCol: 0,
    gridRow: 2,
    slots: [
      { wallSide: "south", offset: -0.45, height: 1.8 },
      { wallSide: "south", offset: 0.45, height: 1.8 },
      { wallSide: "west", offset: -0.45, height: 1.8 },
      { wallSide: "west", offset: 0.45, height: 1.8 },
    ],
  },
  {
    id: 5,
    name: "Sagalassos",
    subtitle: "3 eser",
    artworkIds: [19, 20, 21],
    gridCol: 1,
    gridRow: 2,
    slots: [
      { wallSide: "south", offset: -0.45, height: 1.8 },
      { wallSide: "south", offset: 0.45, height: 1.8 },
      { wallSide: "east", offset: 0, height: 1.8 },
    ],
  },
];

// ── Door connections between adjacent rooms ──
export const DOORS: DoorConnection[] = [
  { roomA: 0, roomB: 1, wallSideA: "east", wallSideB: "west" },
  { roomA: 0, roomB: 2, wallSideA: "south", wallSideB: "north" },
  { roomA: 1, roomB: 3, wallSideA: "south", wallSideB: "north" },
  { roomA: 2, roomB: 3, wallSideA: "east", wallSideB: "west" },
  { roomA: 2, roomB: 4, wallSideA: "south", wallSideB: "north" },
  { roomA: 3, roomB: 5, wallSideA: "south", wallSideB: "north" },
  { roomA: 4, roomB: 5, wallSideA: "east", wallSideB: "west" },
];

// Helper to get room center in world coordinates
export function getRoomCenter(room: RoomConfig): [number, number, number] {
  return [room.gridCol * ROOM_SIZE, 0, -room.gridRow * ROOM_SIZE];
}
