import type { Artwork } from "./types";

/* ──────────────────────────────────────────────────────────────────────────────
   ~170 eser — hafta bazlı.  Görsel yolu: /images/workshop/modern-sanat/week-N/
   Görseller henüz yoksa placeholder olarak boş string kalabilir.
   ────────────────────────────────────────────────────────────────────────────── */

const W = "/images/workshop/modern-sanat";

/* ── Hafta 1 · Empresyonizm ── */
export const WEEK_1_ARTWORKS: Artwork[] = [
  { id: "w1-01", title: "Impression, Sunrise", titleTr: "İzlenim, Gündoğumu", artist: "Claude Monet", year: "1872", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "48 × 63 cm", location: "Musée Marmottan Monet, Paris", image: `${W}/week-1/impression-sunrise.webp`, description: "Akıma adını veren tablo. Le Havre limanında gün doğumunun anlık izlenimi.", funFact: "Eleştirmen Louis Leroy bu tabloyu alay etmek için 'Empresyonist' diye adlandırdı — isim kaldı.", technique: "Kısa, hızlı fırça darbeleri ile ışık yansımaları", week: 1 },
  { id: "w1-02", title: "Luncheon of the Boating Party", titleTr: "Sandalcıların Öğle Yemeği", artist: "Pierre-Auguste Renoir", year: "1881", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "130 × 173 cm", location: "Phillips Collection, Washington", image: `${W}/week-1/boating-party.webp`, description: "Seine nehri kıyısında arkadaş grubunun neşeli öğle yemeği sahnesi.", funFact: "Tablodaki kadın ve köpek, Renoir'ın gelecekteki eşi Aline Charigot.", technique: "Sıcak tonlar, doğal ışık altında figür grupları", week: 1 },
  { id: "w1-03", title: "A Bar at the Folies-Bergère", titleTr: "Folies-Bergère'de Bar", artist: "Édouard Manet", year: "1882", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "96 × 130 cm", location: "Courtauld Gallery, Londra", image: `${W}/week-1/folies-bergere.webp`, description: "Manet'nin son büyük eseri. Ayna yansımasındaki tutarsızlık bilinçli bir tercih.", funFact: "Ayna yansıması fiziksel olarak imkânsız — Manet bunu bilerek yaptı.", technique: "Ayna ile derinlik yanılsaması, geniş fırça darbeleri", week: 1 },
  { id: "w1-04", title: "Water Lilies", titleTr: "Nilüferler", artist: "Claude Monet", year: "1906", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "89 × 93 cm", location: "Art Institute of Chicago", image: `${W}/week-1/water-lilies.webp`, description: "Monet'nin Giverny bahçesindeki havuzu konu alan 250 tablodan biri.", funFact: "Monet katarakt ameliyatı sonrası bazı tabloları yeniden boyadı.", technique: "Büyük tuval, suyun yüzeyinde renk yansımaları", week: 1 },
  { id: "w1-05", title: "Dance at Le Moulin de la Galette", titleTr: "Moulin de la Galette'te Dans", artist: "Pierre-Auguste Renoir", year: "1876", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "131 × 175 cm", location: "Musée d'Orsay, Paris", image: `${W}/week-1/moulin-galette.webp`, description: "Montmartre'daki açık hava dansının ışık-gölge oyunu.", funFact: "Tablo 1990'da 78 milyon dolara satılarak o dönemin rekorunu kırdı.", technique: "Benekli güneş ışığı (dappled light), pastel tonlar", week: 1 },
  { id: "w1-06", title: "The Dance Class", titleTr: "Dans Dersi", artist: "Edgar Degas", year: "1874", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "83 × 77 cm", location: "Metropolitan Museum, New York", image: `${W}/week-1/dance-class.webp`, description: "Degas'nın bale serisinden. Prova anındaki doğal pozlar.", funFact: "Degas kendini 'Empresyonist' değil 'Realist' olarak tanımlıyordu.", technique: "Asimetrik kompozisyon, yapay ışık, hareketi dondurma", week: 1 },
  { id: "w1-07", title: "Rouen Cathedral Series", titleTr: "Rouen Katedrali Serisi", artist: "Claude Monet", year: "1894", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", location: "Çeşitli müzeler", image: `${W}/week-1/rouen-cathedral.webp`, description: "Aynı katedralin farklı saatlerde 30+ versiyonu — ışığın etkisinin kanıtı.", funFact: "Monet katedrali karşısındaki bir dükkândan izleyerek boyadı.", technique: "Kalın boya katmanları (impasto), ışığa göre değişen renk paleti", week: 1 },
  { id: "w1-08", title: "The Cradle", titleTr: "Beşik", artist: "Berthe Morisot", year: "1872", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "56 × 46 cm", location: "Musée d'Orsay, Paris", image: `${W}/week-1/the-cradle.webp`, description: "Morisot'nun kız kardeşini bebeğine bakarken resmettiği hassas portre.", funFact: "İlk Empresyonist sergide (1874) yer alan tek kadın sanatçıydı.", technique: "Yumuşak fırça darbeleri, şeffaf tül detayı", week: 1 },
  { id: "w1-09", title: "Boulevard Montmartre at Night", titleTr: "Gece Montmartre Bulvarı", artist: "Camille Pissarro", year: "1897", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "53 × 65 cm", location: "National Gallery, Londra", image: `${W}/week-1/montmartre-night.webp`, description: "Pissarro'nun otel penceresinden gördüğü gece Paris'i.", funFact: "Pissarro tüm 8 Empresyonist sergiye katılan tek sanatçıdır.", technique: "Gece ışıkları, yağmurlu yüzeyde yansıma", week: 1 },
  { id: "w1-10", title: "The Starry Night", titleTr: "Yıldızlı Gece", artist: "Vincent van Gogh", year: "1889", movement: "Post-Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "74 × 92 cm", location: "MoMA, New York", image: `${W}/week-1/starry-night.webp`, description: "Van Gogh'un Saint-Rémy akıl hastanesinden gördüğü gece manzarası. Post-Empresyonizm köprüsü.", funFact: "Van Gogh bu tabloyu 'başarısız bir deney' olarak gördü.", technique: "Girdaplı fırça darbeleri, yoğun impasto", week: 1 },
  { id: "w1-11", title: "A Sunday Afternoon on the Island of La Grande Jatte", titleTr: "Grande Jatte Adası'nda Bir Pazar Öğleden Sonrası", artist: "Georges Seurat", year: "1886", movement: "Neo-Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "208 × 308 cm", location: "Art Institute of Chicago", image: `${W}/week-1/grande-jatte.webp`, description: "Puantilizmin manifestosu — binlerce küçük nokta ile oluşturulmuş dev tuval.", funFact: "Tablo 2 yılda tamamlandı ve yaklaşık 3.5 milyon nokta içerir.", technique: "Puantilizm / Noktacılık (Divisionism)", week: 1 },
  { id: "w1-12", title: "The Card Players", titleTr: "Kâğıt Oyuncuları", artist: "Paul Cézanne", year: "1895", movement: "Post-Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "47 × 57 cm", location: "Musée d'Orsay, Paris", image: `${W}/week-1/card-players.webp`, description: "Cézanne'ın Aix-en-Provence köylülerini resmettiği sade ama güçlü kompozisyon.", funFact: "Bu serinin bir versiyonu 2011'de 250 milyon dolara satıldı — o dönemin rekoru.", technique: "Geometrik sadeleştirme, sıcak-soğuk renk dengesi", week: 1 },
  { id: "w1-13", title: "Olympia", titleTr: "Olympia", artist: "Édouard Manet", year: "1863", movement: "Empresyonizm öncüsü", medium: "Tuval üzerine yağlıboya", dimensions: "130 × 190 cm", location: "Musée d'Orsay, Paris", image: `${W}/week-1/olympia.webp`, description: "Manet'nin Paris salonunu sarsan eseri — modern sanatın kıvılcımı.", funFact: "Salon'da sergilendiğinde skandal yarattı ve güvenlik konulması gerekti.", technique: "Düz renk alanları, minimal gölgeleme, doğrudan bakış", week: 1 },
  { id: "w1-14", title: "The Japanese Bridge", titleTr: "Japon Köprüsü", artist: "Claude Monet", year: "1899", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "81 × 101 cm", location: "National Gallery, Londra", image: `${W}/week-1/japanese-bridge.webp`, description: "Giverny bahçesindeki Japon köprüsü — Monet'nin en ikonik motiflerinden.", funFact: "Monet, bahçesini 'en güzel başyapıtım' olarak tanımlıyordu.", technique: "Yansıma ve simetri, yeşil tonların zenginliği", week: 1 },
  { id: "w1-15", title: "Bal du moulin de la Galette (study)", titleTr: "Moulin de la Galette Eskizi", artist: "Pierre-Auguste Renoir", year: "1876", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "78 × 114 cm", location: "Ordrupgaard, Kopenhag", image: `${W}/week-1/moulin-study.webp`, description: "Büyük tablonun ön çalışması — daha spontane fırça darbeleri.", technique: "Hızlı eskiz tekniği, ışık lekeleri", week: 1 },
  { id: "w1-16", title: "The Absinthe Drinker", titleTr: "Absint İçen", artist: "Edgar Degas", year: "1876", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "92 × 68 cm", location: "Musée d'Orsay, Paris", image: `${W}/week-1/absinthe.webp`, description: "Café de la Nouvelle-Athènes'de yalnızlık ve melankolinin portresi.", funFact: "Modeller aslında oyuncu Ellen Andrée ve gravürcü Marcellin Desboutin.", technique: "Off-center kompozisyon, boş alan kullanımı", week: 1 },
  { id: "w1-17", title: "Haystacks Series", titleTr: "Saman Balyaları Serisi", artist: "Claude Monet", year: "1891", movement: "Empresyonizm", medium: "Tuval üzerine yağlıboya", location: "Çeşitli müzeler", image: `${W}/week-1/haystacks.webp`, description: "25 tablodan oluşan seri — aynı konu, farklı mevsim ve saat.", funFact: "Bir tanesi 2019'da 110.7 milyon dolara satıldı.", technique: "Aynı motifin ışığa göre renk değişimi", week: 1 },
];

/* ── Hafta 2 · Kübizm ── */
export const WEEK_2_ARTWORKS: Artwork[] = [
  { id: "w2-01", title: "Les Demoiselles d'Avignon", titleTr: "Avignonlu Kızlar", artist: "Pablo Picasso", year: "1907", movement: "Proto-Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "244 × 234 cm", location: "MoMA, New York", image: `${W}/week-2/demoiselles.webp`, description: "Kübizmi başlatan devrimci eser — beş kadın figürü geometrik ve Afrika maskesi etkisi.", funFact: "Picasso'nun yakın arkadaşları bile tabloyu ilk gördüğünde şok oldu.", technique: "Çoklu bakış açısı, geometrik parçalanma, Afrika sanatı etkisi", week: 2 },
  { id: "w2-02", title: "Violin and Candlestick", titleTr: "Keman ve Şamdan", artist: "Georges Braque", year: "1910", movement: "Analitik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "61 × 50 cm", location: "San Francisco Museum of Modern Art", image: `${W}/week-2/violin-candlestick.webp`, description: "Analitik Kübizm'in doruk noktası — nesne tanınmaz hale gelene dek parçalanmış.", technique: "Monokromatik palet, küçük geometrik düzlemler", week: 2 },
  { id: "w2-03", title: "Still Life with Chair Caning", titleTr: "Hasır Örgülü Sandalye ile Natürmort", artist: "Pablo Picasso", year: "1912", movement: "Sentetik Kübizm", medium: "Yağlıboya, muşamba, ip", dimensions: "29 × 37 cm", location: "Musée Picasso, Paris", image: `${W}/week-2/chair-caning.webp`, description: "Sanat tarihindeki ilk kolaj — gerçek malzeme tuvale yapıştırılmış.", funFact: "Oval tuval, masanın şeklini taklit eder. İp çerçeve yerine geçer.", technique: "Kolaj tekniği, karışık malzeme", week: 2 },
  { id: "w2-04", title: "Guernica", titleTr: "Guernica", artist: "Pablo Picasso", year: "1937", movement: "Kübizm / Politik Sanat", medium: "Tuval üzerine yağlıboya", dimensions: "349 × 776 cm", location: "Museo Reina Sofía, Madrid", image: `${W}/week-2/guernica.webp`, description: "İspanya İç Savaşı'nda Guernica kasabasının bombalanmasına tepki. Savaşın dehşetinin simgesi.", funFact: "Bir Nazi subayı 'Bunu siz mi yaptınız?' diye sorduğunda Picasso 'Hayır, siz yaptınız' dedi.", technique: "Grisaille (gri tonlar), büyük format, sembolik figürler", week: 2 },
  { id: "w2-05", title: "The Portuguese", titleTr: "Portekizli", artist: "Georges Braque", year: "1911", movement: "Analitik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "117 × 81 cm", location: "Kunstmuseum Basel", image: `${W}/week-2/the-portuguese.webp`, description: "Kübist tablolara ilk kez harf ve rakam eklenen eser.", technique: "Stencil harfler, monokromatik kahverengi tonlar", week: 2 },
  { id: "w2-06", title: "Portrait of Ambroise Vollard", titleTr: "Ambroise Vollard Portresi", artist: "Pablo Picasso", year: "1910", movement: "Analitik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "92 × 65 cm", location: "Pushkin Museum, Moskova", image: `${W}/week-2/vollard-portrait.webp`, description: "Ünlü galerici Vollard'ın kübist portresi — yüz yüzlerce parçaya bölünmüş.", funFact: "Vollard tablonun beğenilmeyeceğinden korkuyordu ama Picasso 'herkes sizi tanıyacak' dedi.", technique: "Küçük faseta düzlemler, tonal harmoni", week: 2 },
  { id: "w2-07", title: "Breakfast", titleTr: "Kahvaltı", artist: "Juan Gris", year: "1914", movement: "Sentetik Kübizm", medium: "Tuval üzerine yağlıboya, kâğıt kolaj", dimensions: "81 × 60 cm", location: "MoMA, New York", image: `${W}/week-2/breakfast-gris.webp`, description: "Gris'in renkli ve düzenli sentetik kübizmi — Picasso ve Braque'tan daha sistematik.", technique: "Kolaj, canlı renkler, net geometrik bölünme", week: 2 },
  { id: "w2-08", title: "Three Musicians", titleTr: "Üç Müzisyen", artist: "Pablo Picasso", year: "1921", movement: "Sentetik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "201 × 223 cm", location: "MoMA, New York", image: `${W}/week-2/three-musicians.webp`, description: "Sentetik Kübizm'in zirve eseri — üç karnaval müzisyeni düz renk alanlarıyla.", funFact: "Üç figürün Picasso, Apollinaire ve Max Jacob'ı temsil ettiği düşünülür.", technique: "Düz, parlak renk alanları, kolaj estetiği", week: 2 },
  { id: "w2-09", title: "Woman with a Guitar", titleTr: "Gitarlı Kadın", artist: "Georges Braque", year: "1913", movement: "Sentetik Kübizm", medium: "Tuval üzerine yağlıboya, kömür", dimensions: "130 × 74 cm", location: "Musée National d'Art Moderne, Paris", image: `${W}/week-2/woman-guitar-braque.webp`, description: "Braque'ın sentetik döneme geçişini simgeleyen figür çalışması.", technique: "Doku taklitleri (faux bois), kâğıt yapıştırma etkisi", week: 2 },
  { id: "w2-10", title: "The City", titleTr: "Şehir", artist: "Fernand Léger", year: "1919", movement: "Tübüler Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "231 × 298 cm", location: "Philadelphia Museum of Art", image: `${W}/week-2/the-city-leger.webp`, description: "Léger'in mekanik ve endüstriyel Kübizmi — tübüler formlar ve parlak renkler.", technique: "Silindirik formlar, endüstriyel estetik, canlı renkler", week: 2 },
  { id: "w2-11", title: "Simultaneous Windows on the City", titleTr: "Şehre Eşzamanlı Pencereler", artist: "Robert Delaunay", year: "1912", movement: "Orfik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "46 × 40 cm", location: "Hamburger Kunsthalle", image: `${W}/week-2/simultaneous-windows.webp`, description: "Delaunay'ın renk ve ışık odaklı Kübizmi — Eyfel Kulesi prismatik parçalanma.", technique: "Eşzamanlı kontrast, renk diskleri", week: 2 },
  { id: "w2-12", title: "Weeping Woman", titleTr: "Ağlayan Kadın", artist: "Pablo Picasso", year: "1937", movement: "Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "61 × 50 cm", location: "Tate Modern, Londra", image: `${W}/week-2/weeping-woman.webp`, description: "Guernica'nın devamı niteliğinde — savaşın bireysel acısı.", funFact: "Model Dora Maar, Picasso'nun o dönemki sevgilisi ve kendisi de fotoğrafçıydı.", technique: "Keskin açılar, çarpıcı renk kontrastları", week: 2 },
  { id: "w2-13", title: "Ma Jolie", titleTr: "Güzelim", artist: "Pablo Picasso", year: "1912", movement: "Analitik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "100 × 65 cm", location: "MoMA, New York", image: `${W}/week-2/ma-jolie.webp`, description: "Picasso'nun sevgilisine adanmış — soyutlamanın sınırında figür.", technique: "Karmaşık düzlem örtüşmeleri, nota ve harf ekleri", week: 2 },
  { id: "w2-14", title: "Houses at l'Estaque", titleTr: "L'Estaque'da Evler", artist: "Georges Braque", year: "1908", movement: "Proto-Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "73 × 60 cm", location: "Kunstmuseum Bern", image: `${W}/week-2/estaque-houses.webp`, description: "Eleştirmen Vauxcelles'in 'küpler' dediği eser — Kübizm adını buradan aldı.", funFact: "Matisse jüride bu tabloları 'küçük küpler' diye tanımlamıştı.", technique: "Cézanne'vari geometrik sadeleştirme", week: 2 },
  { id: "w2-15", title: "Glass, Guitar, and Bottle", titleTr: "Bardak, Gitar ve Şişe", artist: "Juan Gris", year: "1914", movement: "Sentetik Kübizm", medium: "Tuval üzerine yağlıboya, kolaj", dimensions: "92 × 60 cm", location: "Tate, Londra", image: `${W}/week-2/glass-guitar-gris.webp`, description: "Gris'in geometrik düzeni — nesneler net biçimde ayrılmış ama birleşik.", technique: "Düzgün geometrik bölmeler, kolaj, temiz konturlar", week: 2 },
  { id: "w2-16", title: "Girl with a Mandolin", titleTr: "Mandolinli Kız", artist: "Pablo Picasso", year: "1910", movement: "Analitik Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "100 × 74 cm", location: "MoMA, New York", image: `${W}/week-2/girl-mandolin.webp`, description: "Fanny Tellier'in portresi — analitik kübizmin erken dönemi.", technique: "Yarı-şeffaf düzlemler, figür-zemin birleşmesi", week: 2 },
  { id: "w2-17", title: "Contrast of Forms", titleTr: "Biçimlerin Kontrastı", artist: "Fernand Léger", year: "1913", movement: "Kübizm", medium: "Tuval üzerine yağlıboya", dimensions: "130 × 97 cm", location: "MoMA, New York", image: `${W}/week-2/contrast-forms.webp`, description: "Léger'in tamamen soyuta yaklaştığı tübüler kompozisyon.", technique: "Silindir ve koni formları, ana renkler", week: 2 },
];

/* ── Hafta 3 · Dadaizm ── */
export const WEEK_3_ARTWORKS: Artwork[] = [
  { id: "w3-01", title: "Fountain", titleTr: "Çeşme", artist: "Marcel Duchamp", year: "1917", movement: "Dadaizm", medium: "Porselen pisuar (readymade)", location: "Orijinal kayıp; replikalar çeşitli müzelerde", image: `${W}/week-3/fountain.webp`, description: "Sanat tarihinin en tartışmalı eseri — ters çevrilmiş bir pisuar, 'R. Mutt' imzalı.", funFact: "Orijinal eser atıldı veya kayboldu — bugün gördüklerimiz 1964 replikaları.", technique: "Readymade (hazır nesne) — seçim sanatçının eylemi", week: 3 },
  { id: "w3-02", title: "Cut with the Kitchen Knife", titleTr: "Mutfak Bıçağıyla Kesilmiş", artist: "Hannah Höch", year: "1919", movement: "Dadaizm", medium: "Fotomontaj", dimensions: "114 × 90 cm", location: "Nationalgalerie, Berlin", image: `${W}/week-3/kitchen-knife.webp`, description: "Weimar Cumhuriyeti'ni eleştiren dev fotomontaj — kadın hakları ve politika iç içe.", funFact: "Berlin Dada grubu Höch'ü sergiye almak istemedi — Hausmann onu savundu.", technique: "Fotomontaj, kolaj, gazete ve dergi kesintileri", week: 3 },
  { id: "w3-03", title: "L.H.O.O.Q.", titleTr: "L.H.O.O.Q.", artist: "Marcel Duchamp", year: "1919", movement: "Dadaizm", medium: "Kalem, Mona Lisa reprodüksiyonu", dimensions: "19 × 13 cm", location: "Özel koleksiyon", image: `${W}/week-3/lhooq.webp`, description: "Mona Lisa'ya bıyık ve sakal çizilmiş — yüksek sanat alaycılığı.", funFact: "Harfler Fransızca okunduğunda kaba bir cümle oluşturur.", technique: "Appropriation (sahiplenme), hazır imaj üzerine müdahale", week: 3 },
  { id: "w3-04", title: "Gift", titleTr: "Hediye", artist: "Man Ray", year: "1921", movement: "Dadaizm", medium: "Ütü, çivi", dimensions: "15 × 9 × 12 cm", location: "MoMA, New York (replika)", image: `${W}/week-3/gift-manray.webp`, description: "Ütünün altına çakılmış çiviler — işlevsizleştirilmiş günlük nesne.", funFact: "Orijinal ilk sergiden çalındı; Man Ray onlarca replika yaptı.", technique: "Objet trouvé, işlev bozma", week: 3 },
  { id: "w3-05", title: "Merzbau", titleTr: "Merzbau", artist: "Kurt Schwitters", year: "1923–1937", movement: "Dadaizm / Merz", medium: "Karışık malzeme enstalasyon", location: "Yok edildi (Hannover)", image: `${W}/week-3/merzbau.webp`, description: "Schwitters'ın evini dolduran dev enstalasyon — çöp ve buluntu nesnelerden.", funFact: "II. Dünya Savaşı'nda bombalanarak yok oldu. Fotoğraflar ve yeniden yapımlar kaldı.", technique: "Assamblaj, mekâna yayılan kolaj", week: 3 },
  { id: "w3-06", title: "The Elephant Celebes", titleTr: "Fil Celebes", artist: "Max Ernst", year: "1921", movement: "Dadaizm / Proto-Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "125 × 108 cm", location: "Tate Modern, Londra", image: `${W}/week-3/elephant-celebes.webp`, description: "Mekanik fil figürü — Dada'dan Sürrealizm'e geçiş eseri.", funFact: "Başlık, Alman çocuk tekerlemesinden gelir.", technique: "Kolaj mantığı ile resim, rüya imgesi", week: 3 },
  { id: "w3-07", title: "Rayograph", titleTr: "Rayograf", artist: "Man Ray", year: "1922", movement: "Dadaizm", medium: "Jelatin gümüş baskı (fotogram)", dimensions: "24 × 18 cm", location: "MoMA, New York", image: `${W}/week-3/rayograph.webp`, description: "Kamerasız fotoğraf — nesneler doğrudan fotoğraf kâğıdına yerleştirilmiş.", funFact: "Man Ray bu tekniği tesadüfen, karanlık odada kâğıt üzerinde nesne bırakarak keşfetti.", technique: "Fotogram (kamerasız fotoğraf)", week: 3 },
  { id: "w3-08", title: "Bicycle Wheel", titleTr: "Bisiklet Tekerleği", artist: "Marcel Duchamp", year: "1913", movement: "Proto-Dada", medium: "Bisiklet tekerleği, tabure", dimensions: "127 × 64 cm", location: "MoMA, New York (replika)", image: `${W}/week-3/bicycle-wheel.webp`, description: "İlk readymade — bisiklet tekerleği tabureye monte edilmiş.", funFact: "Duchamp bunu yaparken henüz 'readymade' kavramını adlandırmamıştı.", technique: "Readymade, işlevsel nesnenin sanat bağlamına taşınması", week: 3 },
  { id: "w3-09", title: "Karawane (poem)", titleTr: "Karawane (şiir)", artist: "Hugo Ball", year: "1916", movement: "Dadaizm", medium: "Ses şiiri / tipografi", location: "Cabaret Voltaire, Zürih", image: `${W}/week-3/karawane.webp`, description: "Anlamsız hecelerden oluşan ses şiiri — dilin kendisini sorgulayan performans.", funFact: "Ball bunu karton bir kostüm içinde Cabaret Voltaire'de okudu.", technique: "Ses şiiri, tipografik deneme", week: 3 },
  { id: "w3-10", title: "The Spirit of Our Time", titleTr: "Zamanımızın Ruhu", artist: "Raoul Hausmann", year: "1920", movement: "Dadaizm", medium: "Assamblaj (manken kafası, çeşitli nesneler)", dimensions: "33 × 21 × 20 cm", location: "Centre Pompidou, Paris", image: `${W}/week-3/spirit-of-time.webp`, description: "Manken kafasına yapıştırılmış cetvel, saat mekanizması, cüzdan — 'düşünmeyen insan' eleştirisi.", technique: "Assamblaj, obje trouvé", week: 3 },
  { id: "w3-11", title: "The Rope Dancer Accompanies Herself with Her Shadows", titleTr: "İp Dansçısı Gölgeleriyle Kendine Eşlik Eder", artist: "Man Ray", year: "1916", movement: "Proto-Dada", medium: "Tuval üzerine yağlıboya", dimensions: "132 × 186 cm", location: "MoMA, New York", image: `${W}/week-3/rope-dancer.webp`, description: "Man Ray'in resim ile soyut form arasında denge kurduğu erken çalışma.", technique: "Düz renk alanları, organik-geometrik denge", week: 3 },
  { id: "w3-12", title: "Dada Head", titleTr: "Dada Başı", artist: "Sophie Taeuber-Arp", year: "1920", movement: "Dadaizm", medium: "Boyalı ahşap", dimensions: "24 cm yükseklik", location: "Centre Pompidou, Paris", image: `${W}/week-3/dada-head.webp`, description: "Torna ile şekillendirilmiş soyut baş — Dada heykelinin simgesi.", funFact: "Taeuber-Arp aynı zamanda tekstil tasarımcısı ve dansçıydı.", technique: "Boyalı ahşap heykel, geometrik soyutlama", week: 3 },
  { id: "w3-13", title: "The Large Glass", titleTr: "Büyük Cam", artist: "Marcel Duchamp", year: "1915–1923", movement: "Dadaizm", medium: "Yağlıboya, kurşun folyo, cam", dimensions: "277 × 176 cm", location: "Philadelphia Museum of Art", image: `${W}/week-3/large-glass.webp`, description: "8 yıllık çalışma — cam paneller üzerine mekanik ve erotik ikonografi.", funFact: "Nakliye sırasında cam kırıldı — Duchamp kırıkları eserin bir parçası kabul etti.", technique: "Cam üzerine karışık teknik, şans eseri kırıklar", week: 3 },
  { id: "w3-14", title: "Untitled (Squares Arranged according to the Laws of Chance)", titleTr: "İsimsiz (Tesadüf Yasalarına Göre Düzenlenmiş Kareler)", artist: "Jean Arp", year: "1917", movement: "Dadaizm", medium: "Yırtık kâğıt kolaj", dimensions: "49 × 35 cm", location: "MoMA, New York", image: `${W}/week-3/arp-chance.webp`, description: "Kâğıt parçalarını havaya atarak oluşturulmuş kolaj — rastlantının sanatı.", funFact: "Arp'ın gerçekten kâğıtları rastgele atıp atmadığı tartışmalıdır.", technique: "Rastlantısal kompozisyon, yırtık kâğıt kolaj", week: 3 },
];

/* ── Hafta 4 · Sürrealizm ── */
export const WEEK_4_ARTWORKS: Artwork[] = [
  { id: "w4-01", title: "The Persistence of Memory", titleTr: "Belleğin Azmi", artist: "Salvador Dalí", year: "1931", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "24 × 33 cm", location: "MoMA, New York", image: `${W}/week-4/persistence-memory.webp`, description: "Eriyen saatler — zamanın göreliliğinin en ikonik imgesi.", funFact: "Tablo çok küçük: sadece 24×33 cm. Dalí bunu iki saatte bitirdiğini söyledi.", technique: "Hiperrealist detay + imkânsız imgeler", week: 4 },
  { id: "w4-02", title: "The Son of Man", titleTr: "İnsanoğlu", artist: "René Magritte", year: "1964", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "116 × 89 cm", location: "Özel koleksiyon", image: `${W}/week-4/son-of-man.webp`, description: "Yüzünü yeşil elma kapatan takım elbiseli adam — görünür ile gizli arasındaki gerilim.", funFact: "Magritte 'Her şey gördüğümüzün ardında bir şey gizler' dedi.", technique: "Foto-gerçekçi resim, paradoksal obje yerleştirme", week: 4 },
  { id: "w4-03", title: "The Two Fridas", titleTr: "İki Frida", artist: "Frida Kahlo", year: "1939", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "174 × 173 cm", location: "Museo de Arte Moderno, Mexico City", image: `${W}/week-4/two-fridas.webp`, description: "Boşanma sonrası çift otoportre — açık kalpler, birleşik damar.", funFact: "Kahlo 'Ben sürrealist değilim, rüyalarımı değil gerçekliğimi boyuyorum' dedi.", technique: "Sembolik otoportre, anatomik detay, duygusal anlatım", week: 4 },
  { id: "w4-04", title: "The Treachery of Images", titleTr: "İmgelerin İhaneti", artist: "René Magritte", year: "1929", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "63 × 93 cm", location: "LACMA, Los Angeles", image: `${W}/week-4/treachery-images.webp`, description: "'Ceci n'est pas une pipe' — Bu bir pipo değildir. Temsil ile gerçeklik ayrımı.", funFact: "Magritte haklıydı — o bir pipo değil, bir piponun resmi.", technique: "Dil-görüntü çelişkisi, felsefi resim", week: 4 },
  { id: "w4-05", title: "Europe After the Rain II", titleTr: "Yağmur Sonrası Avrupa II", artist: "Max Ernst", year: "1942", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "54 × 148 cm", location: "Wadsworth Atheneum, Hartford", image: `${W}/week-4/europe-after-rain.webp`, description: "Savaş sonrası harap Avrupa'nın sürreal manzarası — organik ve mekanik formlar.", technique: "Dekalkomani (boya sıkıştırma), kazıma, rastlantısal dokular", week: 4 },
  { id: "w4-06", title: "The Elephants", titleTr: "Filler", artist: "Salvador Dalí", year: "1948", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "49 × 60 cm", location: "Özel koleksiyon", image: `${W}/week-4/elephants-dali.webp`, description: "Örümcek bacaklı filler — güç ve kırılganlık paradoksu.", technique: "İnce uzun formlar, perspektif bozma, ıssız manzara", week: 4 },
  { id: "w4-07", title: "The Eye of Silence", titleTr: "Sessizliğin Gözü", artist: "Max Ernst", year: "1943–1944", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "108 × 141 cm", location: "Washington University Gallery of Art", image: `${W}/week-4/eye-of-silence.webp`, description: "Yabancı bir gezegenin manzarası gibi — organik ve mineral formlar.", technique: "Dekalkomani, otomatik teknikler", week: 4 },
  { id: "w4-08", title: "Mama, Papa is Wounded!", titleTr: "Anne, Baba Yaralı!", artist: "Yves Tanguy", year: "1927", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "92 × 73 cm", location: "MoMA, New York", image: `${W}/week-4/mama-papa.webp`, description: "Tanımlanamayan biyomorfik formların uçsuz bucaksız düzlükte dansı.", technique: "Biyomorfik soyutlama, derin perspektif, yumuşak gölgeler", week: 4 },
  { id: "w4-09", title: "Object (Le Déjeuner en fourrure)", titleTr: "Nesne (Kürklü Kahvaltı)", artist: "Meret Oppenheim", year: "1936", movement: "Sürrealizm", medium: "Kürk kaplı fincan, tabak ve kaşık", location: "MoMA, New York", image: `${W}/week-4/fur-cup.webp`, description: "Kürk kaplı çay fincanı — dokunma ve iğrenme arasındaki sürreal gerilim.", funFact: "Oppenheim bunu 26 yaşında yaptı — sürrealizmin en ikonik objesi oldu.", technique: "Objet surréaliste, malzeme çelişkisi", week: 4 },
  { id: "w4-10", title: "The Burning Giraffe", titleTr: "Yanan Zürafa", artist: "Salvador Dalí", year: "1937", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "35 × 27 cm", location: "Kunstmuseum Basel", image: `${W}/week-4/burning-giraffe.webp`, description: "Çekmeceli kadın figürü ve arka planda alev alan zürafa — Freudyen sembolizm.", technique: "İnce detay, sembolik figür, dramatik arka plan", week: 4 },
  { id: "w4-11", title: "I and the Village", titleTr: "Ben ve Köy", artist: "Marc Chagall", year: "1911", movement: "Proto-Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "192 × 151 cm", location: "MoMA, New York", image: `${W}/week-4/i-and-village.webp`, description: "Chagall'ın Vitebsk anıları — rüya mantığıyla köy yaşamı.", technique: "Şeffaf katmanlar, ters yerçekimi, masal imgesi", week: 4 },
  { id: "w4-12", title: "Self-Portrait with Thorn Necklace", titleTr: "Dikenli Kolyeli Otoportre", artist: "Frida Kahlo", year: "1940", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "62 × 48 cm", location: "Harry Ransom Center, Austin", image: `${W}/week-4/kahlo-thorn.webp`, description: "Boynunda dikenli kolye, siyah kedi ve maymunla — acının sembolik portresi.", technique: "Sembolik ikonografi, canlı renkler, otoportre geleneği", week: 4 },
  { id: "w4-13", title: "The Human Condition", titleTr: "İnsanlık Durumu", artist: "René Magritte", year: "1933", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "100 × 81 cm", location: "National Gallery of Art, Washington", image: `${W}/week-4/human-condition.webp`, description: "Pencere önündeki tablo ile manzara birleşiyor — gerçeklik temsili paradoksu.", technique: "Trompe-l'œil, meta-resim, algı yanılsaması", week: 4 },
  { id: "w4-14", title: "The Great Masturbator", titleTr: "Büyük Mastürbatör", artist: "Salvador Dalí", year: "1929", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "110 × 150 cm", location: "Museo Reina Sofía, Madrid", image: `${W}/week-4/great-masturbator.webp`, description: "Dalí'nin bilinçaltı dünyasının haritası — arzu, korku ve metamorfoz.", technique: "Hiperrealist detay, biyomorfik form, çağrışım zinciri", week: 4 },
  { id: "w4-15", title: "Birthday", titleTr: "Doğum Günü", artist: "Dorothea Tanning", year: "1942", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "102 × 65 cm", location: "Philadelphia Museum of Art", image: `${W}/week-4/birthday-tanning.webp`, description: "Çıplak otoportre, fantastik yaratık ve sonsuz kapılar — kadın sürrealizmin simgesi.", technique: "Detaylı figüratif resim, fantastik unsurlar", week: 4 },
  { id: "w4-16", title: "The Harlequin's Carnival", titleTr: "Arleken'in Karnavalı", artist: "Joan Miró", year: "1925", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "66 × 93 cm", location: "Albright-Knox Gallery, Buffalo", image: `${W}/week-4/harlequin-carnival.webp`, description: "Canlı, oyunsu biçimler ve yaratıklar — Miró'nun otomatik çizim yaklaşımı.", technique: "Biyomorfik formlar, spontane çizgi, canlı renk", week: 4 },
  { id: "w4-17", title: "Swans Reflecting Elephants", titleTr: "Filleri Yansıtan Kuğular", artist: "Salvador Dalí", year: "1937", movement: "Sürrealizm", medium: "Tuval üzerine yağlıboya", dimensions: "51 × 77 cm", location: "Cavalier Galleries", image: `${W}/week-4/swans-elephants.webp`, description: "Su yüzeyinde kuğular fillere dönüşür — Dalí'nin 'paranoyak-eleştirel' yöntemi.", technique: "Çift imge (double image), yansıma ile metamorfoz", week: 4 },
];

/* ── Hafta 5 · De Stijl & Bauhaus ── */
export const WEEK_5_ARTWORKS: Artwork[] = [
  { id: "w5-01", title: "Composition with Red, Blue and Yellow", titleTr: "Kırmızı, Mavi ve Sarı ile Kompozisyon", artist: "Piet Mondrian", year: "1930", movement: "De Stijl", medium: "Tuval üzerine yağlıboya", dimensions: "46 × 46 cm", location: "Kunsthaus Zürich", image: `${W}/week-5/mondrian-rby.webp`, description: "Mondrian'ın neoplastisist manifestosu — sadece ana renkler ve dik çizgiler.", technique: "Siyah ızgara, ana renkler, asimetrik denge", week: 5 },
  { id: "w5-02", title: "Broadway Boogie Woogie", titleTr: "Broadway Boogie Woogie", artist: "Piet Mondrian", year: "1943", movement: "De Stijl", medium: "Tuval üzerine yağlıboya", dimensions: "127 × 127 cm", location: "MoMA, New York", image: `${W}/week-5/broadway-boogie.webp`, description: "New York'un ızgara sistemi ve caz ritmi — Mondrian'ın son başyapıtı.", funFact: "Mondrian caz müziğe tutkuyla bağlıydı ve stüdyosunda sürekli dans ederdi.", technique: "Kesintili renkli çizgiler, ritim, siyah çizgilerin yokluğu", week: 5 },
  { id: "w5-03", title: "Counter-Composition V", titleTr: "Karşı-Kompozisyon V", artist: "Theo van Doesburg", year: "1924", movement: "De Stijl", medium: "Tuval üzerine yağlıboya", dimensions: "100 × 100 cm", location: "Stedelijk Museum, Amsterdam", image: `${W}/week-5/counter-composition.webp`, description: "Mondrian'a meydan okuma — çapraz çizgiler, dinamik gerilim.", funFact: "Mondrian bu çapraz kullanımı kabul etmedi ve Van Doesburg ile yollarını ayırdı.", technique: "45 derece döndürülmüş kareler, çapraz dinamizm", week: 5 },
  { id: "w5-04", title: "Red and Blue Chair", titleTr: "Kırmızı-Mavi Sandalye", artist: "Gerrit Rietveld", year: "1917", movement: "De Stijl", medium: "Boyalı ahşap", location: "Çeşitli müzeler", image: `${W}/week-5/red-blue-chair.webp`, description: "De Stijl felsefesinin mobilyaya dönüşmüş hali — resim üç boyut kazandı.", technique: "Ortogonal birleşim, ana renkler, işlevsel heykel", week: 5 },
  { id: "w5-05", title: "Composition VIII", titleTr: "Kompozisyon VIII", artist: "Wassily Kandinsky", year: "1923", movement: "Bauhaus", medium: "Tuval üzerine yağlıboya", dimensions: "140 × 201 cm", location: "Solomon R. Guggenheim Museum, New York", image: `${W}/week-5/composition-viii.webp`, description: "Bauhaus döneminin geometrik soyutlama zirvesi — daire, üçgen, çizgi.", funFact: "Kandinsky 'Point and Line to Plane' kitabını Bauhaus'ta yazdı.", technique: "Geometrik formlar, renk-biçim ilişkisi", week: 5 },
  { id: "w5-06", title: "Tableau I", titleTr: "Tablo I", artist: "Piet Mondrian", year: "1921", movement: "De Stijl", medium: "Tuval üzerine yağlıboya", dimensions: "103 × 100 cm", location: "Museum Ludwig, Köln", image: `${W}/week-5/tableau-i.webp`, description: "Olgun neoplastisizm — beyaz alanlar ve kalın siyah çizgiler arasında denge.", technique: "Siyah ızgara, sınırlı renk, asimetrik harmoni", week: 5 },
  { id: "w5-07", title: "Yellow-Red-Blue", titleTr: "Sarı-Kırmızı-Mavi", artist: "Wassily Kandinsky", year: "1925", movement: "Bauhaus", medium: "Tuval üzerine yağlıboya", dimensions: "128 × 201 cm", location: "Centre Pompidou, Paris", image: `${W}/week-5/yellow-red-blue.webp`, description: "Sol taraf geometrik düzen, sağ taraf organik kaos — Kandinsky'nin denge arayışı.", technique: "Geometrik-organik karşıtlık, renk teorisi uygulaması", week: 5 },
  { id: "w5-08", title: "Fire in the Evening", titleTr: "Akşam Ateşi", artist: "Paul Klee", year: "1929", movement: "Bauhaus", medium: "Karton üzerine yağlıboya", dimensions: "34 × 33 cm", location: "MoMA, New York", image: `${W}/week-5/fire-evening.webp`, description: "Klee'nin renk kuramı çalışmalarının yansıması — sıcak-soğuk geçişler.", technique: "Renk ızgarası, mozaik etkisi, ton geçişleri", week: 5 },
  { id: "w5-09", title: "Rietveld Schröder House", titleTr: "Rietveld Schröder Evi", artist: "Gerrit Rietveld", year: "1924", movement: "De Stijl", medium: "Mimari", location: "Utrecht, Hollanda (UNESCO)", image: `${W}/week-5/schroder-house.webp`, description: "De Stijl mimarisinin manifestosu — açık plan, kayar duvarlar, ana renkler.", funFact: "Truus Schröder ev boyunca hareketli duvarlar istedikçe Rietveld uyguladı.", technique: "Ortogonal düzlemler, renk kodlama, açık plan", week: 5 },
  { id: "w5-10", title: "Bauhaus Building Dessau", titleTr: "Bauhaus Binası Dessau", artist: "Walter Gropius", year: "1926", movement: "Bauhaus", medium: "Mimari", location: "Dessau, Almanya (UNESCO)", image: `${W}/week-5/bauhaus-dessau.webp`, description: "Bauhaus okulunun ikonik binası — cam perde duvar ve asimetrik plan.", funFact: "Naziler 1933'te Bauhaus'u kapattı; öğretmenler ABD'ye göçtü.", technique: "Cam perde duvar, asimetrik kütle, fonksiyonel tasarım", week: 5 },
  { id: "w5-11", title: "Several Circles", titleTr: "Birkaç Daire", artist: "Wassily Kandinsky", year: "1926", movement: "Bauhaus", medium: "Tuval üzerine yağlıboya", dimensions: "140 × 140 cm", location: "Solomon R. Guggenheim Museum, New York", image: `${W}/week-5/several-circles.webp`, description: "Koyu fon üzerinde yüzen daireler — kozmik düzen hissi.", technique: "Daire formları, şeffaflık, kozmik kompozisyon", week: 5 },
  { id: "w5-12", title: "Senecio", titleTr: "Senecio (Yaşlanan Adam)", artist: "Paul Klee", year: "1922", movement: "Bauhaus", medium: "Tuval üzerine yağlıboya", dimensions: "41 × 38 cm", location: "Kunstmuseum Basel", image: `${W}/week-5/senecio.webp`, description: "Geometrik yüz portresi — çocuksu sadelik ve derin ifade.", funFact: "Klee, Bauhaus'ta 10 yıl ders verdi ve 9.000'den fazla eser üretti.", technique: "Geometrik sadeleştirme, renk blokları, maske etkisi", week: 5 },
  { id: "w5-13", title: "Composition A", titleTr: "Kompozisyon A", artist: "Piet Mondrian", year: "1923", movement: "De Stijl", medium: "Tuval üzerine yağlıboya", dimensions: "90 × 91 cm", location: "Galleria Nazionale d'Arte Moderna, Roma", image: `${W}/week-5/composition-a.webp`, description: "Büyük kırmızı alan ile beyaz denge — Mondrian'ın minimal zirve eseri.", technique: "Büyük renk alanı, minimal ızgara", week: 5 },
  { id: "w5-14", title: "Light Prop for an Electric Stage", titleTr: "Elektrikli Sahne için Işık Sahne Düzeneği", artist: "László Moholy-Nagy", year: "1930", movement: "Bauhaus", medium: "Kinetik heykel (metal, cam, motor)", location: "Harvard Art Museums", image: `${W}/week-5/light-prop.webp`, description: "Motorla dönen metal ve cam — ışık ve gölge ile hareket eden heykel.", funFact: "Moholy-Nagy ışığı resmin yerine koyabileceğine inanıyordu.", technique: "Kinetik sanat, ışık-gölge oyunu, endüstriyel malzeme", week: 5 },
  { id: "w5-15", title: "Twittering Machine", titleTr: "Cıvıldayan Makine", artist: "Paul Klee", year: "1922", movement: "Bauhaus", medium: "Yağlı transfer çizim, suluboya, mürekkep", dimensions: "64 × 48 cm", location: "MoMA, New York", image: `${W}/week-5/twittering-machine.webp`, description: "Krank kollu kuş makinesi — doğa ile teknoloji arasında mizahi köprü.", technique: "Çizgisel humor, suluboya zemin, mekanik-organik birleşim", week: 5 },
  { id: "w5-16", title: "Rietveld Buffet", titleTr: "Rietveld Büfe", artist: "Gerrit Rietveld", year: "1919", movement: "De Stijl", medium: "Boyalı ahşap mobilya", location: "Centraal Museum, Utrecht", image: `${W}/week-5/rietveld-buffet.webp`, description: "Asimetrik açık raflar ve renk kodlu detaylar — De Stijl mobilya tasarımı.", technique: "Ortogonal yapı, asimetri, ana renk aksanları", week: 5 },
];

/* ── Hafta 6 · Soyut Ekspresyonizm ── */
export const WEEK_6_ARTWORKS: Artwork[] = [
  { id: "w6-01", title: "No. 5, 1948", titleTr: "No. 5, 1948", artist: "Jackson Pollock", year: "1948", movement: "Soyut Ekspresyonizm", medium: "Sunta üzerine yağlıboya, emaye, alüminyum boya", dimensions: "244 × 122 cm", location: "Özel koleksiyon", image: `${W}/week-6/no5-pollock.webp`, description: "Pollock'un drip tekniğinin doruk noktası — 2006'da 140 milyon dolara satıldı.", technique: "Drip painting, aksiyon resmi", week: 6 },
  { id: "w6-02", title: "No. 61 (Rust and Blue)", titleTr: "No. 61 (Pas ve Mavi)", artist: "Mark Rothko", year: "1953", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "294 × 232 cm", location: "Museum of Contemporary Art, Los Angeles", image: `${W}/week-6/rothko-61.webp`, description: "Dev renk blokları — Rothko'nun 'trajedi, coşku ve kıyamet' ifadesi.", funFact: "Rothko tablolarının 45 cm'den yakın izlenmesini istiyordu.", technique: "Renk alanı resmi, bulanık kenarlar, çoklu boya katmanı", week: 6 },
  { id: "w6-03", title: "Woman I", titleTr: "Kadın I", artist: "Willem de Kooning", year: "1952", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "193 × 147 cm", location: "MoMA, New York", image: `${W}/week-6/woman-i.webp`, description: "Agresif fırça darbeleriyle kadın figürü — soyut ile figüratif arasında.", funFact: "De Kooning bu tabloyu 2 yıl boyunca defalarca silip yeniden boyadı.", technique: "Jestüel fırça darbeleri, figür-soyutlama gerilimi", week: 6 },
  { id: "w6-04", title: "Autumn Rhythm (Number 30)", titleTr: "Sonbahar Ritmi", artist: "Jackson Pollock", year: "1950", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine emaye", dimensions: "267 × 526 cm", location: "Metropolitan Museum, New York", image: `${W}/week-6/autumn-rhythm.webp`, description: "5 metre genişliğinde drip resim — Pollock'un en büyük eserlerinden.", technique: "Drip, sıçratma, yere serili tuval", week: 6 },
  { id: "w6-05", title: "Mahoning", titleTr: "Mahoning", artist: "Franz Kline", year: "1956", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "204 × 254 cm", location: "Whitney Museum, New York", image: `${W}/week-6/mahoning.webp`, description: "Siyah-beyaz dev fırça darbeleri — endüstriyel güç ve enerji.", funFact: "Kline'ın ilhamı kendi çizimlerinin projektörde büyütülmüş halini görmesiydi.", technique: "Büyük fırça, siyah-beyaz kontrast, mimari güç", week: 6 },
  { id: "w6-06", title: "Milkweed", titleTr: "Sütotu", artist: "Lee Krasner", year: "1955", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "211 × 178 cm", location: "Albright-Knox Gallery, Buffalo", image: `${W}/week-6/milkweed.webp`, description: "Krasner'ın cesur, büyük format çalışması — organik formlar ve güçlü renk.", funFact: "Krasner yıllarca Pollock'un karısı olarak gölgede kaldı.", technique: "Organik jestüel formlar, kalın boya", week: 6 },
  { id: "w6-07", title: "Vir Heroicus Sublimis", titleTr: "Yüce Kahraman Adam", artist: "Barnett Newman", year: "1951", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "242 × 542 cm", location: "MoMA, New York", image: `${W}/week-6/vir-heroicus.webp`, description: "Dev kırmızı yüzey üzerinde ince dikey 'zip' çizgileri — saf renk deneyimi.", technique: "Renk alanı, zip (dikey şerit), büyük format", week: 6 },
  { id: "w6-08", title: "Elegy to the Spanish Republic No. 110", titleTr: "İspanya Cumhuriyeti'ne Ağıt No. 110", artist: "Robert Motherwell", year: "1971", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine akrilik, kömür", dimensions: "208 × 290 cm", location: "Solomon R. Guggenheim Museum, New York", image: `${W}/week-6/elegy-110.webp`, description: "Siyah ovallerden oluşan seri — İspanya İç Savaşı'na 150+ tablo ile ağıt.", technique: "Siyah-beyaz, organik ovaller, ritmik tekrar", week: 6 },
  { id: "w6-09", title: "Lavender Mist: Number 1, 1950", titleTr: "Lavanta Sisi: No. 1", artist: "Jackson Pollock", year: "1950", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya, emaye, alüminyum", dimensions: "221 × 300 cm", location: "National Gallery of Art, Washington", image: `${W}/week-6/lavender-mist.webp`, description: "Pollock'un en lirik eseri — pembe-gümüş-beyaz katmanlar.", technique: "All-over kompozisyon, ince drip katmanları", week: 6 },
  { id: "w6-10", title: "Black in Deep Red", titleTr: "Koyu Kırmızıda Siyah", artist: "Mark Rothko", year: "1957", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "176 × 137 cm", location: "Özel koleksiyon", image: `${W}/week-6/black-deep-red.webp`, description: "Rothko'nun olgunluk döneminin karanlık tonu — meditasyon ve matem.", technique: "Yumuşak kenarlı renk blokları, koyu palet", week: 6 },
  { id: "w6-11", title: "Blue Poles", titleTr: "Mavi Direkler", artist: "Jackson Pollock", year: "1952", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine emaye, alüminyum, cam", dimensions: "212 × 489 cm", location: "National Gallery of Australia, Canberra", image: `${W}/week-6/blue-poles.webp`, description: "Kaotik drip üzerine dikey mavi çizgiler — yapı ve kaos dengesi.", funFact: "Avustralya 1973'te 1.3 milyon dolara satın aldığında büyük skandal koptu.", technique: "Drip + kontrollü dikey şeritler", week: 6 },
  { id: "w6-12", title: "Mountains and Sea", titleTr: "Dağlar ve Deniz", artist: "Helen Frankenthaler", year: "1952", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "220 × 298 cm", location: "National Gallery of Art, Washington", image: `${W}/week-6/mountains-sea.webp`, description: "Soak-stain tekniğinin ilk büyük eseri — boya tuvale emdirilmiş.", funFact: "Bu eser Color Field resmine ilham verdi; Morris Louis ve Kenneth Noland bu tablodan etkilendi.", technique: "Soak-stain (emme tekniği), ham tuval, akışkan renk", week: 6 },
  { id: "w6-13", title: "Excavation", titleTr: "Kazı", artist: "Willem de Kooning", year: "1950", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya, emaye", dimensions: "206 × 257 cm", location: "Art Institute of Chicago", image: `${W}/week-6/excavation.webp`, description: "De Kooning'in en karmaşık soyut eseri — gizli figürler ve iç içe formlar.", technique: "Jestüel soyutlama, kat kat boya, gizli figürasyon", week: 6 },
  { id: "w6-14", title: "Onement I", titleTr: "Birlik I", artist: "Barnett Newman", year: "1948", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "69 × 41 cm", location: "MoMA, New York", image: `${W}/week-6/onement-i.webp`, description: "Newman'ın ilk 'zip' eseri — dikey çizgi ile yaratılışın başlangıcı.", technique: "Zip (bant maskesi ile dikey çizgi), monokromatik alan", week: 6 },
  { id: "w6-15", title: "The Seasons", titleTr: "Mevsimler", artist: "Lee Krasner", year: "1957", movement: "Soyut Ekspresyonizm", medium: "Tuval üzerine yağlıboya", dimensions: "237 × 518 cm", location: "Whitney Museum, New York", image: `${W}/week-6/seasons-krasner.webp`, description: "Pollock'un ölümünden sonra Krasner'ın en cesur dönemi — dev boyut ve enerji.", technique: "Büyük format, organik formlar, cesur hareket", week: 6 },
  { id: "w6-16", title: "Rothko Chapel", titleTr: "Rothko Şapeli", artist: "Mark Rothko", year: "1971", movement: "Soyut Ekspresyonizm", medium: "14 büyük tuval (mekâna özel)", location: "Rothko Chapel, Houston", image: `${W}/week-6/rothko-chapel.webp`, description: "Rothko'nun son projesi — koyu mor-siyah tablolarla kaplı meditasyon mekânı.", funFact: "Rothko şapelin açılışını göremedi; 1970'te intihar etti.", technique: "Site-specific enstalasyon, monokromatik karanlık", week: 6 },
];

/* ── Hafta 7 · Pop Art ── */
export const WEEK_7_ARTWORKS: Artwork[] = [
  { id: "w7-01", title: "Campbell's Soup Cans", titleTr: "Campbell's Çorba Kutuları", artist: "Andy Warhol", year: "1962", movement: "Pop Art", medium: "Tuval üzerine sentetik polimer", dimensions: "32 adet, 51 × 41 cm", location: "MoMA, New York", image: `${W}/week-7/campbells-soup.webp`, description: "32 çorba kutusu — seri üretim estetiğinin sanat galerisine girişi.", funFact: "Warhol her gün öğle yemeğinde Campbell's çorbası içtiğini söyledi.", technique: "Serigrafi, seri üretim estetiği", week: 7 },
  { id: "w7-02", title: "Whaam!", titleTr: "Whaam!", artist: "Roy Lichtenstein", year: "1963", movement: "Pop Art", medium: "Tuval üzerine akrilik, yağlıboya", dimensions: "173 × 406 cm", location: "Tate Modern, Londra", image: `${W}/week-7/whaam.webp`, description: "Çizgi roman karesi olarak savaş sahnesi — ben-day noktaları ve konuşma balonu.", technique: "Ben-Day noktaları, kalın kontur, çizgi roman estetiği", week: 7 },
  { id: "w7-03", title: "Marilyn Diptych", titleTr: "Marilyn Diptik", artist: "Andy Warhol", year: "1962", movement: "Pop Art", medium: "Tuval üzerine akrilik, serigrafi", dimensions: "205 × 290 cm", location: "Tate Modern, Londra", image: `${W}/week-7/marilyn-diptych.webp`, description: "50 Marilyn portresi — şöhret, ölüm ve tekrarın hipnotik etkisi.", funFact: "Monroe'nun ölümünden haftalar sonra yapıldı.", technique: "Serigrafi tekrarı, renk variasyonları, solma efekti", week: 7 },
  { id: "w7-04", title: "Floor Burger", titleTr: "Yer Hamburgeri", artist: "Claes Oldenburg", year: "1962", movement: "Pop Art", medium: "Tuval, köpük, karton", dimensions: "132 × 213 cm", location: "Art Gallery of Ontario, Toronto", image: `${W}/week-7/floor-burger.webp`, description: "Dev yumuşak hamburger heykeli — gündelik nesnenin abartılı büyütülmesi.", technique: "Yumuşak heykel, ölçek değiştirme, gündelik nesne", week: 7 },
  { id: "w7-05", title: "Infinity Mirror Room", titleTr: "Sonsuz Ayna Odası", artist: "Yayoi Kusama", year: "1965", movement: "Pop Art / Enstalasyon", medium: "Aynalar, ışıklar", location: "Çeşitli müzeler (tekrarlanan enstalasyon)", image: `${W}/week-7/infinity-room.webp`, description: "Sonsuz yansımalı ayna odası — benliğin evrende erimesi.", funFact: "Kusama bu eserleri psikiyatrik deneyimlerinden ilham alarak yaptı.", technique: "Ayna enstalasyonu, sonsuz tekrar, ışık", week: 7 },
  { id: "w7-06", title: "Just What Is It That Makes Today's Homes So Different, So Appealing?", titleTr: "Bugünkü Evleri Bu Kadar Farklı, Bu Kadar Çekici Kılan Nedir?", artist: "Richard Hamilton", year: "1956", movement: "Pop Art", medium: "Kolaj", dimensions: "26 × 25 cm", location: "Kunsthalle Tübingen", image: `${W}/week-7/hamilton-collage.webp`, description: "Pop Art'ın manifestosu sayılan kolaj — tüm tüketim sembolleri tek karede.", funFact: "Bu küçük kolaj, Pop Art teriminin ilk kez kullanıldığı eser olarak kabul edilir.", technique: "Kolaj, reklam imgesi, popüler kültür sembolizmi", week: 7 },
  { id: "w7-07", title: "Drowning Girl", titleTr: "Boğulan Kız", artist: "Roy Lichtenstein", year: "1963", movement: "Pop Art", medium: "Tuval üzerine yağlıboya, sentetik polimer", dimensions: "172 × 170 cm", location: "MoMA, New York", image: `${W}/week-7/drowning-girl.webp`, description: "Melodramatik çizgi roman karesi — 'Brad'den yardım istemektense boğulmayı tercih ederim!'", technique: "Ben-Day noktaları, konuşma balonu, dramatik sahne", week: 7 },
  { id: "w7-08", title: "Brillo Boxes", titleTr: "Brillo Kutuları", artist: "Andy Warhol", year: "1964", movement: "Pop Art", medium: "Serigrafi mürekkep, boyalı ahşap", dimensions: "44 × 43 × 36 cm", location: "Çeşitli müzeler", image: `${W}/week-7/brillo-boxes.webp`, description: "Süpermarket kutuları olarak heykel — sanat ve sıradan nesne ayrımını sorgulama.", funFact: "Arthur Danto bu eseri 'sanat dünyasının sonu'nun simgesi olarak yorumladı.", technique: "Serigrafi, endüstriyel malzeme, appropriation", week: 7 },
  { id: "w7-09", title: "Green Coca-Cola Bottles", titleTr: "Yeşil Coca-Cola Şişeleri", artist: "Andy Warhol", year: "1962", movement: "Pop Art", medium: "Tuval üzerine akrilik, serigrafi", dimensions: "210 × 145 cm", location: "Whitney Museum, New York", image: `${W}/week-7/green-coca-cola.webp`, description: "112 Coca-Cola şişesi — 'Zengin de fakir de aynı şişeyi içer' diyen Warhol.", technique: "Serigrafi tekrarı, ızgara düzeni", week: 7 },
  { id: "w7-10", title: "My Bed", titleTr: "Yatağım", artist: "Tracey Emin", year: "1998", movement: "Pop Art / YBA", medium: "Enstalasyon (yatak, kişisel eşyalar)", location: "Tate, Londra", image: `${W}/week-7/my-bed.webp`, description: "Emin'in depresyon döneminde bıraktığı dağınık yatağı — Pop'tan çağdaşa köprü.", technique: "Hazır nesne enstalasyon, otobiyografik sanat", week: 7 },
  { id: "w7-11", title: "Love", titleTr: "Love", artist: "Robert Indiana", year: "1966", movement: "Pop Art", medium: "Yağlıboya", dimensions: "305 × 305 × 152 cm (heykel versiyonu)", location: "Indianapolis Museum of Art", image: `${W}/week-7/love-indiana.webp`, description: "LOVE yazısı eğik O harfi ile — Pop Art'ın en tanınmış sembolü.", technique: "Tipografi, cesur renk, basit form", week: 7 },
  { id: "w7-12", title: "Shot Sage Blue Marilyn", titleTr: "Vurulan Adaçayı Mavi Marilyn", artist: "Andy Warhol", year: "1964", movement: "Pop Art", medium: "Tuval üzerine serigrafi", dimensions: "101 × 101 cm", location: "Özel koleksiyon", image: `${W}/week-7/sage-blue-marilyn.webp`, description: "2022'de 195 milyon dolara satılarak en pahalı 20. yüzyıl eseri oldu.", funFact: "Bir ziyaretçi fabrikada tabloya silahla ateş etti — 'Shot' adı buradan gelir.", technique: "Serigrafi, floresan renk, ikonik portre", week: 7 },
  { id: "w7-13", title: "Pumpkin", titleTr: "Balkabağı", artist: "Yayoi Kusama", year: "1994", movement: "Pop Art / Çağdaş", medium: "Boyalı FRP", dimensions: "200 × 250 cm", location: "Naoshima, Japonya", image: `${W}/week-7/pumpkin-kusama.webp`, description: "Dev sarı balkabağı — Kusama'nın 'ebedi ruh' sembolü, Naoshima ikonu.", technique: "Polka dot pattern, büyük ölçek heykel", week: 7 },
  { id: "w7-14", title: "Flag", titleTr: "Bayrak", artist: "Jasper Johns", year: "1955", movement: "Proto-Pop Art", medium: "Enskaustik, yağlıboya, kolaj", dimensions: "107 × 154 cm", location: "MoMA, New York", image: `${W}/week-7/flag-johns.webp`, description: "Amerikan bayrağı mı, bayrak resmi mi? Johns bu soruyu sormak için boyadı.", funFact: "Johns bir rüyasında kendini bayrak boyarken gördü ve ertesi gün başladı.", technique: "Enskaustik (balmumu), kolaj, tanıdık imge", week: 7 },
  { id: "w7-15", title: "I Was a Rich Man's Plaything", titleTr: "Zengin Bir Adamın Oyuncağıydım", artist: "Eduardo Paolozzi", year: "1947", movement: "Proto-Pop Art", medium: "Kolaj", dimensions: "36 × 24 cm", location: "Tate, Londra", image: `${W}/week-7/rich-mans-plaything.webp`, description: "Amerikan dergi reklamlarından kolaj — 'Pop' kelimesinin ilk göründüğü eser.", funFact: "Bu kolaj, 'Pop' kelimesinin sanatta ilk kullanıldığı yer olarak kabul edilir.", technique: "Kolaj, reklam imgesi, çoklu kültürel referans", week: 7 },
];

/* ── Hafta 8 · Kavramsal Sanat ── */
export const WEEK_8_ARTWORKS: Artwork[] = [
  { id: "w8-01", title: "One and Three Chairs", titleTr: "Bir ve Üç Sandalye", artist: "Joseph Kosuth", year: "1965", movement: "Kavramsal Sanat", medium: "Sandalye, fotoğraf, sözlük tanımı", location: "MoMA, New York", image: `${W}/week-8/one-three-chairs.webp`, description: "Gerçek sandalye + fotoğrafı + sözlük tanımı — 'sandalye' kavramının üç hali.", funFact: "Her sergide yerel bir sandalye kullanılır — eser her seferinde farklı.", technique: "Kavramsal enstalasyon, dil-nesne ilişkisi", week: 8 },
  { id: "w8-02", title: "Wall Drawing #118", titleTr: "Duvar Çizimi #118", artist: "Sol LeWitt", year: "1971", movement: "Kavramsal Sanat", medium: "Kalem, duvar", location: "Çeşitli müzeler (talimat temelli)", image: `${W}/week-8/wall-drawing-118.webp`, description: "Yazılı talimatlar — herkes çizebilir, fikir sanatçınındır.", funFact: "LeWitt çizimlerini kendi yapmadı; asistanlar talimatları uyguluyordu.", technique: "Talimat temelli sanat, tekrarlanabilirlik", week: 8 },
  { id: "w8-03", title: "Cut Piece", titleTr: "Kes Parçası", artist: "Yoko Ono", year: "1964", movement: "Kavramsal / Performans", medium: "Performans", location: "İlk: Yamaichi Concert Hall, Kyoto", image: `${W}/week-8/cut-piece.webp`, description: "Ono sahnede oturur, izleyiciler kıyafetlerini keser — güven ve şiddet.", technique: "Katılımcı performans, talimat sanatı", week: 8 },
  { id: "w8-04", title: "The Artist is Present", titleTr: "Sanatçı Burada", artist: "Marina Abramović", year: "2010", movement: "Performans Sanatı", medium: "Performans (736 saat)", location: "MoMA, New York", image: `${W}/week-8/artist-is-present.webp`, description: "736 saat boyunca ziyaretçilerle göz göze oturma — insan bağlantısının gücü.", funFact: "Eski sevgilisi Ulay karşısına oturduğunda Abramović ağladı.", technique: "Dayanıklılık performansı, göz teması, zaman", week: 8 },
  { id: "w8-05", title: "I Got Up", titleTr: "Kalktım", artist: "On Kawara", year: "1968–1979", movement: "Kavramsal Sanat", medium: "Kartpostal (günlük gönderi)", location: "Çeşitli koleksiyonlar", image: `${W}/week-8/i-got-up.webp`, description: "Her gün iki kişiye kalktığı saati yazan kartpostal — zamanın belgelenmesi.", technique: "Günlük ritüel, posta sistemi, belgeleme", week: 8 },
  { id: "w8-06", title: "Date Paintings (Today Series)", titleTr: "Tarih Resimleri", artist: "On Kawara", year: "1966–2013", movement: "Kavramsal Sanat", medium: "Tuval üzerine liquitex", location: "Çeşitli müzeler", image: `${W}/week-8/date-paintings.webp`, description: "Her gün o günün tarihini boyama — 50 yıl boyunca. Aynı gün bitmezse imha.", funFact: "Kawara tek bir tablonun 8 saatten fazla sürmesine izin vermedi.", technique: "Seri üretim, zaman kaydı, monokrom", week: 8 },
  { id: "w8-07", title: "Grapefruit", titleTr: "Greyfurt", artist: "Yoko Ono", year: "1964", movement: "Kavramsal / Fluxus", medium: "Kitap (talimat parçaları)", location: "Çeşitli baskılar", image: `${W}/week-8/grapefruit.webp`, description: "'Gökyüzünü izle' gibi talimatlardan oluşan kavramsal sanat kitabı.", technique: "Talimat sanatı, metin temelli, hayal gücü", week: 8 },
  { id: "w8-08", title: "Paragraphs on Conceptual Art", titleTr: "Kavramsal Sanat Üzerine Paragraflar", artist: "Sol LeWitt", year: "1967", movement: "Kavramsal Sanat", medium: "Manifesto / metin", location: "Artforum dergisi", image: `${W}/week-8/paragraphs-conceptual.webp`, description: "Kavramsal sanatın manifestosu — 'Fikir makine, sanat ürün olur.'", technique: "Yazı olarak sanat, manifesto", week: 8 },
  { id: "w8-09", title: "An Oak Tree", titleTr: "Bir Meşe Ağacı", artist: "Michael Craig-Martin", year: "1973", movement: "Kavramsal Sanat", medium: "Cam bardak, su, metin", location: "Tate, Londra", image: `${W}/week-8/oak-tree.webp`, description: "Rafta duran su bardağı + 'Bu bir meşe ağacı' metni — inanç ve dönüşüm.", technique: "Ready-made, metin-nesne çelişkisi", week: 8 },
  { id: "w8-10", title: "Erased de Kooning Drawing", titleTr: "Silinmiş De Kooning Çizimi", artist: "Robert Rauschenberg", year: "1953", movement: "Proto-Kavramsal", medium: "Silinmiş çizim üzerine iz, altın yaldız çerçeve", location: "SFMOMA, San Francisco", image: `${W}/week-8/erased-dekooning.webp`, description: "Rauschenberg, de Kooning'den bir çizim isteyip sildi — yaratma yoluyla yok etme.", funFact: "De Kooning silmesi en zor olacak çizimi seçti; Rauschenberg 2 ay sildi.", technique: "Silme eylemi, kavramsal jest, boşluk sanatı", week: 8 },
  { id: "w8-11", title: "Fountain (After Marcel Duchamp)", titleTr: "Çeşme (Marcel Duchamp Sonrası)", artist: "Sherrie Levine", year: "1991", movement: "Kavramsal / Appropriation", medium: "Bronz", location: "Walker Art Center", image: `${W}/week-8/levine-fountain.webp`, description: "Duchamp'ın pisuarının bronz kopyası — kopyanın kopyası, orijinallik sorgusu.", technique: "Appropriation, malzeme dönüşümü", week: 8 },
  { id: "w8-12", title: "Rhythm 0", titleTr: "Ritim 0", artist: "Marina Abramović", year: "1974", movement: "Performans Sanatı", medium: "Performans (72 nesne, 6 saat)", location: "Studio Morra, Napoli", image: `${W}/week-8/rhythm-0.webp`, description: "72 nesne (gül, bıçak, tabanca) ve 6 saat — izleyici ne isterse yapabilir.", funFact: "Biri yüklü tabancayı Abramović'in başına doğrulttu; diğerleri durdurdu.", technique: "Katılımcı performans, riskli etkileşim, güven testi", week: 8 },
];

/* ── Hafta 9 · Performans & Arazi Sanatı ── */
export const WEEK_9_ARTWORKS: Artwork[] = [
  { id: "w9-01", title: "Spiral Jetty", titleTr: "Spiral İskele", artist: "Robert Smithson", year: "1970", movement: "Arazi Sanatı", medium: "Çamur, kristal tuz, bazalt", dimensions: "457 m uzunluk", location: "Great Salt Lake, Utah", image: `${W}/week-9/spiral-jetty.webp`, description: "Tuz gölünde 457 metre uzunluğunda taş spiral — arazi sanatının ikonu.", funFact: "Göl seviyesi yükseldiğinde su altında kalır, alçaldığında tuz kristalleriyle kaplanır.", technique: "Earthwork, site-specific, doğal malzeme", week: 9 },
  { id: "w9-02", title: "Wrapped Reichstag", titleTr: "Sarılmış Reichstag", artist: "Christo & Jeanne-Claude", year: "1995", movement: "Arazi / Çevresel Sanat", medium: "Alüminyum kaplı polipropilen kumaş, ip", location: "Berlin, Almanya", image: `${W}/week-9/wrapped-reichstag.webp`, description: "Alman parlamentosu 100.000 m² kumaşla sarıldı — 24 yıl süren izin süreci.", funFact: "5 milyon ziyaretçi geldi ve tüm maliyet sanatçıların eser satışlarından karşılandı.", technique: "Sarma (wrapping), geçici mekân dönüşümü", week: 9 },
  { id: "w9-03", title: "Silueta Series", titleTr: "Siluet Serisi", artist: "Ana Mendieta", year: "1973–1980", movement: "Beden / Arazi Sanatı", medium: "Toprak, kan, ateş, beden", location: "Iowa / Meksika (efemeral)", image: `${W}/week-9/silueta.webp`, description: "Mendieta'nın beden izini doğaya bırakması — kimlik, köken ve kayıp.", technique: "Beden izi, doğal malzeme, efemeral sanat", week: 9 },
  { id: "w9-04", title: "I Like America and America Likes Me", titleTr: "Amerika'yı Seviyorum ve Amerika Beni Seviyor", artist: "Joseph Beuys", year: "1974", movement: "Performans Sanatı", medium: "Performans (3 gün, çakal ile)", location: "René Block Gallery, New York", image: `${W}/week-9/beuys-coyote.webp`, description: "Beuys 3 gün bir çakal ile kapalı odada yaşadı — doğa-kültür diyalogu.", funFact: "Beuys ABD'ye ambulansla gelip doğrudan galeriye götürüldü — ayağını ABD toprağına basmadı.", technique: "Şamanistik performans, hayvan etkileşimi", week: 9 },
  { id: "w9-05", title: "Roden Crater", titleTr: "Roden Krateri", artist: "James Turrell", year: "1977–devam", movement: "Arazi / Işık Sanatı", medium: "Volkanik krater, ışık", location: "Arizona, ABD", image: `${W}/week-9/roden-crater.webp`, description: "Sönmüş volkana oyulmuş ışık gözlem odaları — gökyüzünü çerçeveleme.", funFact: "Proje 50 yılı aştı ve hâlâ tamamlanmadı.", technique: "Doğal ışık, mekân düzenleme, algı deneyleri", week: 9 },
  { id: "w9-06", title: "The Lightning Field", titleTr: "Yıldırım Tarlası", artist: "Walter De Maria", year: "1977", movement: "Arazi Sanatı", medium: "400 paslanmaz çelik direk", dimensions: "1 mil × 1 km", location: "New Mexico, ABD", image: `${W}/week-9/lightning-field.webp`, description: "Çölde 400 metal direk — yıldırım çekecek şekilde ızgara düzeninde.", funFact: "Ziyaretçiler geceyi orada geçirmeli — günde sadece 6 kişi kabul ediliyor.", technique: "Site-specific enstalasyon, doğa olayı entegrasyonu", week: 9 },
  { id: "w9-07", title: "The Gates", titleTr: "Kapılar", artist: "Christo & Jeanne-Claude", year: "2005", movement: "Çevresel Sanat", medium: "7.503 turuncu kumaş portal", location: "Central Park, New York", image: `${W}/week-9/the-gates.webp`, description: "Central Park'ta 37 km boyunca turuncu kumaş portallar — 26 yıllık izin süreci.", technique: "Geçici site-specific enstalasyon, tekrar", week: 9 },
  { id: "w9-08", title: "Double Negative", titleTr: "Çifte Olumsuz", artist: "Michael Heizer", year: "1969", movement: "Arazi Sanatı", medium: "Kazı (240.000 ton toprak)", dimensions: "457 × 15 × 9 m", location: "Nevada, ABD", image: `${W}/week-9/double-negative.webp`, description: "İki uçurum kenarından 240.000 ton toprak çıkarma — yokluk olarak heykel.", technique: "Büyük ölçek kazı, negatif form, çöl manzarası", week: 9 },
  { id: "w9-09", title: "7000 Oaks", titleTr: "7000 Meşe", artist: "Joseph Beuys", year: "1982", movement: "Sosyal Heykel", medium: "7.000 meşe ağacı + bazalt sütunları", location: "Kassel, Almanya", image: `${W}/week-9/7000-oaks.webp`, description: "Her meşenin yanına bir bazalt sütun — sosyal heykel olarak şehir dönüşümü.", funFact: "Beuys son ağacı dikemedi; oğlu projeyi 1987'de tamamladı.", technique: "Sosyal heykel, çevresel aktivizm, uzun süreç", week: 9 },
  { id: "w9-10", title: "The Weather Project", titleTr: "Hava Projesi", artist: "Olafur Eliasson", year: "2003", movement: "Çağdaş Enstalasyon", medium: "Mono-frekans lambalar, ayna tavan, sis", location: "Tate Modern Turbine Hall, Londra", image: `${W}/week-9/weather-project.webp`, description: "Tate Modern'de yapay güneş — 2 milyon ziyaretçi tavandaki yansımasına baktı.", technique: "Işık enstalasyonu, sis, ayna, algı deneyimi", week: 9 },
  { id: "w9-11", title: "Sun Tunnels", titleTr: "Güneş Tünelleri", artist: "Nancy Holt", year: "1976", movement: "Arazi Sanatı", medium: "4 beton tünel", dimensions: "Her biri 5.5 m uzunluk", location: "Utah, ABD", image: `${W}/week-9/sun-tunnels.webp`, description: "Güneş doğuş/batışına hizalanmış 4 beton tünel — gündönümü çerçeveleme.", technique: "Astronomik hizalama, beton heykel, doğal ışık", week: 9 },
  { id: "w9-12", title: "Floating Piers", titleTr: "Yüzen İskeleler", artist: "Christo & Jeanne-Claude", year: "2016", movement: "Çevresel Sanat", medium: "Yüzen platform, altın kumaş", dimensions: "3 km", location: "Iseo Gölü, İtalya", image: `${W}/week-9/floating-piers.webp`, description: "Göl üzerinde yürüyüş deneyimi — 1.2 milyon ziyaretçi 16 günde.", technique: "Yüzen platform, su üzerinde yürüme deneyimi", week: 9 },
  { id: "w9-13", title: "Tree Mountain", titleTr: "Ağaç Dağı", artist: "Agnes Denes", year: "1996", movement: "Arazi / Ekolojik Sanat", medium: "11.000 ağaç, yapay tepe", location: "Ylöjärvi, Finlandiya", image: `${W}/week-9/tree-mountain.webp`, description: "11.000 kişinin birer ağaç diktiği yapay dağ — 400 yıl koruma altında.", technique: "Katılımcı ekolojik sanat, uzun vadeli proje", week: 9 },
  { id: "w9-14", title: "Untitled (Your Body is a Battleground)", titleTr: "İsimsiz (Bedeniniz Bir Savaş Alanı)", artist: "Barbara Kruger", year: "1989", movement: "Kavramsal / Feminist", medium: "Fotoğraf serigrafi", dimensions: "284 × 284 cm", location: "Broad, Los Angeles", image: `${W}/week-9/your-body.webp`, description: "Cesur tipografi ile feminist manifesto — kadın yüzünün pozitif/negatif ayrımı.", technique: "Büyük format, tipografi, siyah-beyaz fotoğraf", week: 9 },
];

/* ── Hafta 10 · Çağdaş Sanat Panoraması ── */
export const WEEK_10_ARTWORKS: Artwork[] = [
  { id: "w10-01", title: "Untitled (Skull)", titleTr: "İsimsiz (Kafatası)", artist: "Jean-Michel Basquiat", year: "1981", movement: "Neo-Ekspresyonizm", medium: "Akrilik, yağlı pastel boya", dimensions: "205 × 256 cm", location: "Broad, Los Angeles", image: `${W}/week-10/basquiat-skull.webp`, description: "Sokaktan galeriye — grafiti estetiği ile anatomik imgeler.", funFact: "Basquiat 27 yaşında hayatını kaybetti; eserleri bugün 100 milyon doları aşıyor.", technique: "Grafiti, ham ifade, metin-görüntü birleşimi", week: 10 },
  { id: "w10-02", title: "Sunflower Seeds", titleTr: "Ayçiçeği Tohumları", artist: "Ai Weiwei", year: "2010", movement: "Çağdaş / Politik", medium: "100 milyon porselen tohum", location: "Tate Modern, Londra (geçici)", image: `${W}/week-10/sunflower-seeds.webp`, description: "100 milyon elle boyanmış porselen tohum — bireysellik ve kitle üretimi.", funFact: "Her tohum Jingdezhen'de 1.600 işçi tarafından tek tek elle boyandı.", technique: "Enstalasyon, el işçiliği, kitle-birey gerilimi", week: 10 },
  { id: "w10-03", title: "Girl with Balloon", titleTr: "Balonlu Kız", artist: "Banksy", year: "2006", movement: "Sokak Sanatı", medium: "Stencil, sprey boya", location: "Waterloo Bridge, Londra (orijinal); çeşitli", image: `${W}/week-10/girl-balloon.webp`, description: "Kalp şeklinde balon kaçıran kız — umut ve kayıp. Sotheby's'te kendi kendini parçaladı.", funFact: "2018'de müzayedede 1.4 milyon dolara satılırken çerçevedeki gizli kâğıt öğütücü devreye girdi.", technique: "Stencil, sprey boya, sokak sanatı", week: 10 },
  { id: "w10-04", title: "A Subtlety", titleTr: "Bir İncelik", artist: "Kara Walker", year: "2014", movement: "Çağdaş / Politik", medium: "Şeker kaplı polistiren", dimensions: "10.7 m yükseklik", location: "Domino Sugar Factory, Brooklyn (geçici)", image: `${W}/week-10/a-subtlety.webp`, description: "Dev sfenks — şeker, kölelik ve kadın bedeni arasındaki bağ.", technique: "Büyük ölçek heykel, şeker, site-specific", week: 10 },
  { id: "w10-05", title: "The Physical Impossibility of Death in the Mind of Someone Living", titleTr: "Yaşayan Birinin Zihninde Ölümün Fiziksel İmkânsızlığı", artist: "Damien Hirst", year: "1991", movement: "YBA / Çağdaş", medium: "Formaldehit içinde kaplan köpekbalığı", location: "Özel koleksiyon", image: `${W}/week-10/shark-hirst.webp`, description: "Formaldehit tankında köpekbalığı — ölüm, korku ve sanat piyasası.", funFact: "Orijinal köpekbalığı çürüdü ve 2006'da yenisiyle değiştirildi.", technique: "Hayvan konservasyonu, vitrin, şok etkisi", week: 10 },
  { id: "w10-06", title: "Dropping a Han Dynasty Urn", titleTr: "Han Hanedanı Vazosu Düşürme", artist: "Ai Weiwei", year: "1995", movement: "Çağdaş / Kavramsal", medium: "Performans fotoğrafı (triptik)", location: "Çeşitli", image: `${W}/week-10/dropping-urn.webp`, description: "2.000 yıllık vazoyu kasıtlı olarak kırma — geleneğe meydan okuma.", technique: "Performatif yıkım, fotoğraf belgeleme", week: 10 },
  { id: "w10-07", title: "For the Love of God", titleTr: "Tanrı Aşkına", artist: "Damien Hirst", year: "2007", movement: "Çağdaş", medium: "Platin kafatası, 8.601 elmas", location: "Özel koleksiyon", image: `${W}/week-10/love-of-god.webp`, description: "Elmaslarla kaplı gerçek insan kafatası — vanitas geleneğinin modern versiyonu.", funFact: "Satış fiyatı 100 milyon dolar — en pahalı çağdaş sanat eseri iddiası.", technique: "Kıymetli taş, vanitas sembolizmi", week: 10 },
  { id: "w10-08", title: "The Dinner Party", titleTr: "Akşam Yemeği", artist: "Judy Chicago", year: "1979", movement: "Feminist Sanat", medium: "Seramik, tekstil, enstalasyon", dimensions: "Üçgen masa, 14.6 m kenar", location: "Brooklyn Museum, New York", image: `${W}/week-10/dinner-party.webp`, description: "39 tarihi kadın figürü için üçgen masa — feminist sanatın anıtsal eseri.", funFact: "400'den fazla gönüllü 6 yıl boyunca üretimde çalıştı.", technique: "Seramik, nakış, sembolik enstalasyon", week: 10 },
  { id: "w10-09", title: "Cloud Gate", titleTr: "Bulut Kapısı", artist: "Anish Kapoor", year: "2006", movement: "Çağdaş Heykel", medium: "Paslanmaz çelik", dimensions: "10 × 20 × 13 m", location: "Millennium Park, Chicago", image: `${W}/week-10/cloud-gate.webp`, description: "'The Bean' olarak bilinen dev aynalı heykel — şehri yansıtma ve bozma.", funFact: "168 çelik plaka kusursuz kaynak edildi — hiçbir dikiş izi görünmez.", technique: "Aynalı yüzey, yansıma, büyük ölçek", week: 10 },
  { id: "w10-10", title: "Comedian", titleTr: "Komedyen", artist: "Maurizio Cattelan", year: "2019", movement: "Çağdaş / Kavramsal", medium: "Muz, bant", location: "Art Basel Miami Beach", image: `${W}/week-10/comedian.webp`, description: "Duvara bantlanmış muz — 120.000 dolara satılan kavramsal provokasyon.", funFact: "Bir performans sanatçısı muzu duvardan koparıp yedi.", technique: "Ready-made, provokasyon, sanat piyasası eleştirisi", week: 10 },
  { id: "w10-11", title: "Shibboleth", titleTr: "Şibbolet", artist: "Doris Salcedo", year: "2007", movement: "Çağdaş", medium: "Beton zeminde çatlak", dimensions: "167 m", location: "Tate Modern Turbine Hall (geçici)", image: `${W}/week-10/shibboleth.webp`, description: "Müzenin betonunda 167 metrelik çatlak — ayrımcılık ve bölünme metaforu.", technique: "Site-specific müdahale, beton kesme", week: 10 },
  { id: "w10-12", title: "My Lonesome Cowboy", titleTr: "Yalnız Kovboyum", artist: "Takashi Murakami", year: "1998", movement: "Süperflat / Çağdaş", medium: "Fiberglas, demir, yağlıboya", dimensions: "254 cm yükseklik", location: "Özel koleksiyon", image: `${W}/week-10/lonesome-cowboy.webp`, description: "Anime estetiği ile fine art — Japon pop kültürü ve Batı sanat piyasası.", technique: "Süperflat estetik, anime referans, heykel", week: 10 },
  { id: "w10-13", title: "Untitled (We Don't Need Another Hero)", titleTr: "İsimsiz (Bir Kahraman Daha İstemiyoruz)", artist: "Barbara Kruger", year: "1987", movement: "Kavramsal / Feminist", medium: "Fotoğraf serigrafi", location: "Çeşitli", image: `${W}/week-10/another-hero.webp`, description: "Kas gösteren çocuk ve kız — toplumsal cinsiyet rollerinin sorgulanması.", technique: "Siyah-beyaz fotoğraf, kırmızı bant tipografi", week: 10 },
  { id: "w10-14", title: "Balloon Dog (Orange)", titleTr: "Balon Köpek (Turuncu)", artist: "Jeff Koons", year: "1994–2000", movement: "Neo-Pop / Çağdaş", medium: "Ayna cilalı paslanmaz çelik", dimensions: "307 × 363 × 114 cm", location: "Çeşitli müzeler", image: `${W}/week-10/balloon-dog.webp`, description: "Dev aynalı balon köpek — kitsch'in zaferine mi yoksa ironisine mi?", funFact: "2013'te 58.4 milyon dolara satılarak yaşayan sanatçı rekoru kırdı.", technique: "Aynalı çelik, büyük ölçek, kitsch estetik", week: 10 },
  { id: "w10-15", title: "Flower Thrower", titleTr: "Çiçek Atan", artist: "Banksy", year: "2003", movement: "Sokak Sanatı", medium: "Stencil, sprey boya", location: "Kudüs / Batı Şeria duvarı", image: `${W}/week-10/flower-thrower.webp`, description: "Molotof kokteyli yerine çiçek buketi fırlatan maskeli adam — barış mesajı.", technique: "Stencil, sokak sanatı, siyasi mesaj", week: 10 },
  { id: "w10-16", title: "Puppy", titleTr: "Köpek Yavrusu", artist: "Jeff Koons", year: "1992", movement: "Çağdaş", medium: "Çiçekli heykel (çelik, toprak, çiçek)", dimensions: "12.4 m yükseklik", location: "Guggenheim Bilbao", image: `${W}/week-10/puppy-koons.webp`, description: "12 metre boyunda çiçeklerle kaplı terrier heykeli — sanat ve eğlence.", funFact: "Heykel 60.000 canlı çiçek barındırır ve kendi sulama sistemi var.", technique: "Topiyer heykel, büyük ölçek, sezonluk çiçek", week: 10 },
];

/* ── Tüm haftalık export'lar ── */
export const ALL_ARTWORKS: Artwork[] = [
  ...WEEK_1_ARTWORKS,
  ...WEEK_2_ARTWORKS,
  ...WEEK_3_ARTWORKS,
  ...WEEK_4_ARTWORKS,
  ...WEEK_5_ARTWORKS,
  ...WEEK_6_ARTWORKS,
  ...WEEK_7_ARTWORKS,
  ...WEEK_8_ARTWORKS,
  ...WEEK_9_ARTWORKS,
  ...WEEK_10_ARTWORKS,
];

export function getArtworksForWeek(weekNumber: number): Artwork[] {
  return ALL_ARTWORKS.filter((a) => a.week === weekNumber);
}
