-- Pazaryeri: 5 örnek veri
INSERT INTO marketplace_events (title, slug, description, short_description, category, city, district, venue_name, venue_address, organizer_name, organizer_url, organizer_phone, organizer_email, price, price_options, event_date, end_date, duration_note, image_url, max_participants, is_featured, status) VALUES

-- 1. Seramik Atölyesi (Ankara, featured)
(
  'Seramik Atölyesi: İlk Dokunuş',
  'seramik-atolyesi-ilk-dokunus',
  'Seramik sanatına ilk adımınızı atın! Bu başlangıç seviye atölyede çamuru şekillendirmeyi, sırlama tekniklerini ve fırınlama sürecini öğreneceksiniz. Tüm malzemeler dahildir.',
  'Başlangıç seviye seramik atölyesi — çamurdan eser çıkarın.',
  'seramik',
  'Ankara',
  'Çankaya',
  'Toprak Sanat Atölyesi',
  'Tunalı Hilmi Cad. No:42, Çankaya',
  'Toprak Sanat',
  'https://example.com/toprak-sanat',
  '0312 555 1234',
  'info@topraksanat.com',
  750,
  NULL,
  '2026-05-10T14:00:00+03:00',
  '2026-05-10T17:00:00+03:00',
  '3 saat',
  'https://picsum.photos/seed/1/800/600',
  12,
  true,
  'active'
),

-- 2. Yağlıboya Workshop (Ankara)
(
  'Yağlıboya Workshop: Empresyonizm',
  'yagliboya-workshop-empresyonizm',
  'Monet ve Renoir''un tekniklerinden ilham alarak kendi empresyonist tablonuzu yapın. Tuval, boya ve fırça seti dahildir. Orta seviye katılımcılar için uygundur.',
  'Empresyonist tekniklerle kendi tablonuzu yapın.',
  'resim',
  'Ankara',
  'Kızılay',
  'Palet Sanat Evi',
  'Atatürk Bulvarı No:78, Kızılay',
  'Palet Sanat',
  'https://example.com/palet-sanat',
  '0312 555 5678',
  'info@paletsanat.com',
  1200,
  NULL,
  '2026-05-17T10:00:00+03:00',
  '2026-05-17T16:00:00+03:00',
  '6 saat (öğle arası dahil)',
  'https://picsum.photos/seed/2/800/600',
  8,
  false,
  'active'
),

-- 3. Fotoğraf Yürüyüşü (Ankara, ücretsiz)
(
  'Fotoğraf Yürüyüşü: Ankara Kalesi',
  'fotograf-yuruyusu-ankara-kalesi',
  'Ankara Kalesi''nin tarihi sokaklarında fotoğraf çekerek yürüyüş yapıyoruz. Cep telefonu veya fotoğraf makinesi yeterli. Tüm seviyeler hoş geldiniz!',
  'Ankara Kalesi sokaklarında ücretsiz fotoğraf turu.',
  'fotograf',
  'Ankara',
  'Altındağ',
  'Ankara Kalesi Kapısı',
  'Hisar Parkı Girişi, Altındağ',
  'Ankara Fotoğraf Kulübü',
  'https://example.com/ankara-foto',
  '0532 555 9012',
  'foto@ankarafoto.com',
  0,
  NULL,
  '2026-05-24T09:00:00+03:00',
  '2026-05-24T12:00:00+03:00',
  '3 saat',
  'https://picsum.photos/seed/3/800/600',
  25,
  false,
  'active'
),

-- 4. Kaligrafi Atölyesi (İstanbul, price_options)
(
  'Kaligrafi Atölyesi: Osmanlı Hattı',
  'kaligrafi-atolyesi-osmanli-hatti',
  'Osmanlı hat sanatının inceliklerini keşfedin. Kamış kalem ve mürekkep kullanarak temel hatları öğrenin. Başlangıç ve orta seviye.',
  'Osmanlı hat sanatı ile tanışın — kamış kalem ile yazı.',
  'yazarlik',
  'İstanbul',
  'Beyoğlu',
  'Kalem Güzeli Atölyesi',
  'İstiklal Cad. Mis Sok. No:12, Beyoğlu',
  'Kalem Güzeli',
  'https://example.com/kalem-guzeli',
  '0212 555 3456',
  'info@kalemguzeli.com',
  900,
  '[{"label":"Tek Seans","price":900,"note":"Malzeme dahil"},{"label":"4 Seanslık Paket","price":3000,"note":"Haftada 1, malzeme + sertifika"}]',
  '2026-06-01T13:00:00+03:00',
  '2026-06-01T16:00:00+03:00',
  '3 saat',
  'https://picsum.photos/seed/4/800/600',
  10,
  false,
  'active'
),

-- 5. Baskı & Gravür Workshop (İstanbul, price_options)
(
  'Baskı & Gravür Workshop',
  'baski-gravur-workshop',
  'Linol baskı ve gravür tekniklerini uygulamalı olarak öğrenin. Kendi deseninizi çizin, kalıba aktarın ve baskılarınızı alın. Tüm malzemeler dahildir.',
  'Linol baskı ve gravür tekniklerini keşfedin.',
  'resim',
  'İstanbul',
  'Kadıköy',
  'Mürekkep Atölyesi',
  'Moda Cad. No:55, Kadıköy',
  'Mürekkep Kolektif',
  'https://example.com/murekkep',
  '0216 555 7890',
  'hello@murekkep.com',
  1500,
  '[{"label":"Yarım Gün","price":1500,"note":"10:00-13:00, malzeme dahil"},{"label":"Tam Gün","price":2500,"note":"10:00-17:00, öğle yemeği + malzeme dahil"}]',
  '2026-06-07T10:00:00+03:00',
  '2026-06-07T17:00:00+03:00',
  'Yarım gün veya tam gün',
  'https://picsum.photos/seed/5/800/600',
  6,
  false,
  'active'
);
